
import { createTheme } from '@mui/material';
import { Translations } from './types';

export const APP_NAME = "Lux Brasil";
export const COMPANY_INFO = {
  name: "BRASILUX ENTERTAINMENT LTDA",
  fantasy_name: "BRASILUX ENTERTAINMENT",
  cnpj: "61.197.797/0001-53",
  address: "R. Gentil Moreno, 618 - Conj. Hab. Antonio Pedro Ortolan, Sertãozinho - SP, 14.177-255",
  email: "suporte@braillux.com",
  phone: "(16) 99424-4231",
  dpo: "privacidade@braillux.com"
};

// Lux Casino Dark Theme
export const theme = createTheme({
  palette: {
    mode: 'dark',
    primary: {
      main: '#D4AF37', // Metallic Gold
      dark: '#AA8C2C',
      light: '#F3E5AB',
      contrastText: '#000000',
    },
    secondary: {
      main: '#800020', // Burgundy
    },
    background: {
      default: '#050510',
      paper: '#0F121D',   
    },
    text: {
      primary: '#F5F5F5',
      secondary: '#A0A0A0',
    },
    divider: 'rgba(212, 175, 55, 0.2)',
  },
  typography: {
    fontFamily: '"Inter", "Roboto", sans-serif',
    h1: { fontFamily: '"Montserrat", sans-serif', fontWeight: 800, letterSpacing: '-0.02em', textTransform: 'uppercase' },
    h2: { fontFamily: '"Montserrat", sans-serif', fontWeight: 700, letterSpacing: '-0.01em' },
    h3: { fontFamily: '"Montserrat", sans-serif', fontWeight: 700, color: '#D4AF37' },
    h4: { fontFamily: '"Montserrat", sans-serif', fontWeight: 600 },
    h5: { fontFamily: '"Montserrat", sans-serif', fontWeight: 600 },
    h6: { fontFamily: '"Montserrat", sans-serif', fontWeight: 600 },
    button: { fontFamily: '"Montserrat", sans-serif', fontWeight: 700, letterSpacing: 1 },
    overline: { fontFamily: '"Inter", sans-serif', letterSpacing: 2, fontWeight: 600 },
  },
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          borderRadius: 4, 
          padding: '12px 32px',
          textTransform: 'none',
          fontSize: '1rem',
        },
        containedPrimary: {
          background: 'linear-gradient(135deg, #D4AF37 0%, #AA8C2C 100%)',
          color: '#000',
          boxShadow: '0 4px 20px rgba(212, 175, 55, 0.2)',
          animation: 'pulse-gold 2s infinite', 
          '&:hover': {
            background: 'linear-gradient(135deg, #F3E5AB 0%, #D4AF37 100%)',
          },
        },
        outlined: {
            borderWidth: '1px',
            borderColor: '#D4AF37',
            color: '#D4AF37',
        }
      },
    },
    MuiPaper: {
      styleOverrides: {
        root: {
          backgroundImage: 'none',
          backgroundColor: '#0F121D',
          color: '#F5F5F5',
          borderRadius: 12,
          border: '1px solid rgba(255, 255, 255, 0.05)',
        },
      },
    },
    MuiChip: {
      styleOverrides: {
        root: {
          fontWeight: 600,
        }
      }
    }
  },
});

export const TRANSLATIONS: Translations = {
  pt: {
    // General
    loading: "Carregando...",
    error_generic: "Ocorreu um erro. Tente novamente.",
    success: "Sucesso!",
    close: "Fechar",
    btn_close: "FECHAR",
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Salvar",
    copy: "Copiar",
    copied: "Copiado",
    view_all: "VER HISTÓRICO COMPLETO",
    
    // Navigation
    home: "Início",
    dashboard: "Lobby",
    myPrizes: "Minha Carteira",
    vault: "Loja Lux",
    admin: "Administração",
    logout: "Sair",
    login: "Entrar",
    getStarted: "Criar Conta",
    spin: "Roleta Premiada",
    spinsAvailable: "Giros",
    challenge: "Desafios",
    challenges_tab: "Missões",
    redeem: "Resgatar",
    wallet: "Saldo",
    open_wallet: "ABRIR CARTEIRA",
    menu: "MENU",
    language_label: "Idioma",
    lux_coins: "LuxCoins",
    nav_balance: "COINS",
    nav_profile: "PERFIL",
    
    // Status
    status_pending: "Disponível",
    status_requested: "Em Análise",
    status_redeemed: "Pago/Enviado",
    status_label: "Status",
    status_active_user: "Membro Ativo",
    member_area: "ÁREA DE MEMBROS",
    
    // Hero & Landing
    heroTitle: "GIRE E GANHE",
    heroSubtitle: "Aqui na nossa plataforma você pode girar e ganhar na mesma hora, venha fazer parte.",
    landing_badge: "CHEGOU SUA HORA DE GANHAR",
    landing_desc: "A experiência definitiva em sorteios de luxo. Cadastre-se, gire a roleta exclusiva e conquiste prêmios reais instantaneamente com total segurança.",
    btn_already_member: "JÁ SOU MEMBRO",
    stats_active_members: "MEMBROS ATIVOS",
    stats_prizes_paid: "PRÊMIOS PAGOS",
    stats_secure: "SEGURO & AUDITADO",
    why_lux: "POR QUE A LUX BRASIL?",
    exclusive_detail: "Exclusividade em Cada Detalhe",
    cta_title: "Pronto para a sua sorte mudar?",
    cta_subtitle: "Junte-se a milhares de vencedores hoje mesmo.",
    cta_btn: "GIRAR ROLETA AGORA",

    feature_1_title: "Acesso Imediato",
    feature_1_desc: "Cadastre-se e comece a girar a roleta imediatamente para ganhar prêmios.",
    feature_2_title: "Sorteios Verificados",
    feature_2_desc: "Nossos algoritmos garantem total transparência e segurança em cada giro.",
    feature_3_title: "Segurança Global",
    feature_3_desc: "Totalmente compatível com padrões internacionais de proteção de dados.",
    footer_desc: "A plataforma líder em recompensas premium. Transformando sorte em experiências inesquecíveis com segurança e transparência.",
    footer_contact: "CONTATO & SUPORTE",
    footer_address_label: "ENDEREÇO CORPORATIVO",
    footer_rights: "Todos os direitos reservados.",
    footer_legal_title: "LEGAL & COMPLIANCE",
    legal_privacy: "Política de Privacidade",
    legal_terms: "Termos de Uso",
    legal_data: "LGPD & Proteção de Dados",
    legal_rules: "Regras dos Desafios",
    developed_by: "Desenvolvido com Tecnologia Lux Secure™",
    
    // Roulette & Game
    prizes_title: "Minha Carteira & Prêmios",
    prizes_empty: "Você ainda não possui prêmios. Gire a roleta!",
    spin_btn: "GIRAR AGORA",
    spinning: "SORTEANDO...",
    congrats: "Parabéns!",
    try_again_title: "Não foi dessa vez...",
    try_again_desc: "Não desanime, a sorte favorece quem insiste!",
    try_again_cashback_title: "PRÊMIO DE CONSOLAÇÃO",
    try_again_cashback_desc: "Você recebeu +{amount} LuxCoins na sua carteira!",
    you_won: "Você ganhou",
    no_spins_title: "SEM GIROS DISPONÍVEIS",
    no_spins_desc: "Você usou todos os seus giros diários. Complete missões para ganhar mais agora mesmo!",
    btn_go_challenges: "IR PARA MISSÕES",
    next_spin_label: "PRÓXIMO GIRO GRÁTIS",
    recent_activity: "Atividade Recente",
    no_activity: "Nenhuma atividade recente.",
    your_spins: "SEUS GIROS",
    available: "DISPONÍVEIS",
    next_refill_in: "PRÓXIMO REFILL EM",
    ready_to_use: "Você tem giros prontos para usar!",
    go_to_roulette: "IR PARA ROLETA",
    redeem_now: "RESGATAR AGORA",
    add_wallet: "Adicionar à Carteira",
    consolation_prize: "PRÊMIO DE CONSOLAÇÃO",
    you_won_label: "VOCÊ GANHOU",
    balance_updated: "Saldo atualizado na sua carteira.",
    close_and_continue: "FECHAR E CONTINUAR",
    label_code: "CÓDIGO:",
    msg_redemption_sent: "Solicitação enviada. Nosso concierge entrará em contato.",
    
    // Vault / Store
    vault_title: "The Vault",
    vault_subtitle: "Troque seus LuxCoins por giros extras e vantagens.",
    vault_exchange_success: "Troca realizada com sucesso! +1 Giro.",
    vault_exchange_error: "Saldo insuficiente ou erro na troca.",
    exchange_rate: "100 LC = 1 GIRO",
    btn_exchange: "TROCAR AGORA",
    extra_spin: "Giro Extra",
    cost_label: "CUSTO",
    btn_redeem_item: "RESGATAR ITEM",
    label_virtual: "VIRTUAL",
    label_physical: "FÍSICO",
    label_money: "DINHEIRO",
    store_item_spin_name: "Giro Extra",
    store_item_spin_desc: "Troque seus coins por uma nova chance na roleta.",
    store_item_headphone_name: "Headphone Lux Edition",
    store_item_headphone_desc: "Fone de ouvido bluetooth FOO36-BRA. Alta fidelidade sonora.",
    store_item_earbuds_name: "Earbuds TWS Pro",
    store_item_earbuds_desc: "Fone True Wireless FOO42-BRA. Cancelamento de ruído.",
    store_item_money_name: "Prêmio em Dinheiro",
    store_item_money_desc: "Resgate R$ {amount} direto na sua conta. Processamento em até 24h.",
    purchase_success: "Compra realizada! O item \"{item}\" foi adicionado à sua Carteira.",
    purchase_money_success: "Resgate de R${amount} solicitado! Verifique sua Carteira.",

    // Challenges
    challenges_area: "ÁREA OPERACIONAL",
    challenges_title: "Central de Missões",
    challenges_subtitle: "Complete contratos exclusivos, suba de nível e desbloqueie recompensas.",
    tab_daily: "OPERAÇÕES DIÁRIAS",
    tab_weekly: "SEMANAIS",
    tab_monthly: "MENSAIS",
    tab_career: "CARREIRA",
    diff_easy: "INICIANTE",
    diff_medium: "VETERANO",
    diff_hard: "ELITE",
    progress: "PROGRESSO",
    reward_label: "RECOMPENSA",
    btn_completed: "CONCLUÍDO",
    btn_redeem_reward: "RESGATAR",
    btn_proof: "COMPROVAR",
    btn_in_progress: "EM ANDAMENTO",
    proof_dialog_title: "ENVIAR COMPROVANTE",
    proof_dialog_desc: "Insira o link ou descrição da tarefa realizada para validação manual.",
    btn_send_analysis: "ENVIAR PARA ANÁLISE",
    reward_xp: "XP",
    visit_and_validate: "VISITAR E VALIDAR",
    verifying_access: "VERIFICANDO ACESSO...",
    access_validated: "Acesso validado! Recompensa creditada.",
    proof_sent: "Comprovante enviado para análise!",

    // Dashboard & Level
    level_silver: "PRATA",
    level_gold: "OURO",
    level_platinum: "PLATINA",
    level_label: "NÍVEL {level}",
    next_level: "Próximo nível: {xp} XP",
    notification_missions_approved: "Você tem {count} missões aprovadas! Resgate seus prêmios agora.",
    notification_mission_completed: "Missão Concluída: {name}! Recompensa entregue.",

    // Invite System
    invite_program_vip: "PROGRAMA VIP",
    invite_premium: "Indicação Premium",
    invite_active: "Ativo",
    invite_desc: "Convide seus amigos e receba {bonus} para cada cadastro confirmado. Quanto mais amigos, mais chances de ganhar!",
    invite_bonus_highlight: "+1 giro grátis",
    invite_stats_friends: "Amigos",
    invite_stats_spins: "Giros",
    invite_stats_rate: "Taxa",
    invite_link_title: "Seu Link Exclusivo",
    invite_recent_list: "Indicações Recentes",
    invite_share_text: "Venha girar a roleta e ganhar prêmios incríveis na Lux Brasil!",
    status_confirmed: "Bônus Pago",
    status_registered: "Cadastro Validado",
    status_rewarded: "Bônus Recebido",
    status_pending_invite: "Aguardando",
    
    // Admin
    admin_panel: "PAINEL DE CONTROLE",
    admin_title: "ADMINISTRAÇÃO",
    btn_update: "Atualizar",
    tab_users: "USUÁRIOS",
    tab_config: "CONFIG. ROLETA",
    tab_audit: "AUDITORIA",
    search_placeholder: "Buscar por nome, email ou CPF...",
    total_label: "Total",
    table_user: "USUÁRIO",
    table_cpf: "CPF",
    table_balance: "SALDO / GIROS",
    table_ip: "IP ADDRESS",
    table_actions: "AÇÕES",
    status_banned: "BANIDO",
    status_active: "ATIVO",
    new_prize: "NOVO PRÊMIO",
    prize_active: "Ativo na Roleta",
    btn_save: "SALVAR",
    btn_cancel: "CANCELAR",
    lbl_prob: "Probabilidade (0-1)",
    lbl_color: "Cor (Hex)",
    lbl_prize_name: "Nome do Prêmio",
    admin_add_coins: "Adicionar LuxCoins",
    admin_add_spins: "Adicionar Giros",
    admin_coins_amount: "Quantidade de Coins",
    admin_preset_loss: "Não foi dessa vez",
    admin_preset_gold: "Gold",
    admin_preset_silver: "Silver",
    admin_central_requests: "Central de Resgates",
    filter_pending: "Pendentes",
    filter_paid: "Pagos",
    header_date: "DATA",
    header_user: "USUÁRIO",
    header_prize: "PRÊMIO",
    header_code: "CÓDIGO",
    header_status: "STATUS",
    header_action: "AÇÕES",
    type_physical: "Físico",
    type_money: "Dinheiro/LC",
    type_spins: "Giros",
    btn_pay: "Pagar",
    btn_refuse: "Recusar",
    btn_reopen: "Reabrir",
    empty_requests: "Nenhuma solicitação pendente.",
    empty_history: "Nenhum histórico encontrado.",
    stats_total_users: "TOTAL USUÁRIOS",
    stats_coins_circulation: "COINS EM CIRCULAÇÃO",
    stats_banned_users: "USUÁRIOS BANIDOS",
    tip_prize_active: "Dica: Se um prêmio já saiu na roleta, você não conseguirá excluí-lo. Nesse caso, desative a opção 'Ativo na Roleta'.",
    config_roulette: "Configuração da Roleta",
    audit_report: "Relatório de Atividades",
    audit_subtitle: "Registro completo de ações administrativas",
    log_action_update_prize: "Edição de Prêmio",
    log_action_create_prize: "Criação de Prêmio",
    log_action_delete_prize: "Exclusão de Prêmio",
    log_action_ban_user: "Banimento de Usuário",
    log_action_unban_user: "Desbloqueio de Usuário",
    log_action_add_spins: "Crédito de Giros",
    log_action_add_coins: "Crédito de LuxCoins",
    log_action_ban_ip: "Bloqueio de IP",
    log_action_update_redemption: "Status de Solicitação",
    dialog_add_spins_title: "Adicionar Giros",
    dialog_add_coins_title: "Adicionar LuxCoins",
    table_date: "DATA",
    table_prize: "PRÊMIO",
    table_code: "CÓDIGO",
    table_status: "STATUS",
    table_action: "AÇÃO",
    
    // Auth & Errors
    push_title: "Lux Brasil",
    push_body_spin: "Seu giro diário já está disponível!",
    register_title: "Crie sua Conta",
    name_label: "Nome Completo",
    cpf_label: "CPF",
    phone_label: "Celular",
    invite_label: "Código de Convite (Opcional)",
    pass_label: "Senha",
    confirm_pass_label: "Confirmar Senha",
    already_member: "Já é membro?",
    not_member: "Ainda não é membro?",
    forgot_pass: "Esqueceu a senha?",
    create_account_btn: "CRIAR CONTA E GIRAR",
    register_success_check_email: "Conta criada! Verifique seu e-mail.",
    err_req: "Campo obrigatório",
    err_cpf: "CPF inválido",
    err_pass_match: "As senhas não conferem",
    err_invite: "Código de convite inválido",
    auth_email_confirm: "Seu e-mail ainda não foi confirmado.",
    auth_invalid_creds: "E-mail ou senha incorretos.",
    
    // Legal Texts (Placeholders for structure)
    legal_doc_official: "DOCUMENTO LEGAL OFICIAL",
    legal_updated: "Última atualização: {date}",
  },
  
  en: {
    // General
    loading: "Loading...",
    error_generic: "An error occurred. Please try again.",
    success: "Success!",
    close: "Close",
    btn_close: "CLOSE",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    copy: "Copy",
    copied: "Copied",
    view_all: "VIEW FULL HISTORY",

    // Navigation
    home: "Home",
    dashboard: "Lobby",
    myPrizes: "Wallet",
    vault: "Lux Store",
    admin: "Admin",
    logout: "Log Out",
    login: "Login",
    getStarted: "Sign Up",
    spin: "Lucky Wheel",
    spinsAvailable: "Spins",
    challenge: "Challenges",
    challenges_tab: "Missions",
    redeem: "Redeem",
    wallet: "Balance",
    open_wallet: "OPEN WALLET",
    menu: "MENU",
    language_label: "Language",
    lux_coins: "LuxCoins",
    nav_balance: "COINS",
    nav_profile: "PROFILE",

    // Status
    status_pending: "Available",
    status_requested: "In Review",
    status_redeemed: "Paid/Sent",
    status_label: "Status",
    status_active_user: "Active Member",
    member_area: "MEMBER AREA",

    // Hero & Landing
    heroTitle: "SPIN AND WIN",
    heroSubtitle: "Here at our platform you can spin and win instantly, join us.",
    landing_badge: "IT'S YOUR TIME TO WIN",
    landing_desc: "The definitive experience in luxury draws. Sign up, spin the exclusive wheel and win real prizes instantly with total security.",
    btn_already_member: "ALREADY A MEMBER",
    stats_active_members: "ACTIVE MEMBERS",
    stats_prizes_paid: "PRIZES PAID",
    stats_secure: "SECURE & AUDITED",
    why_lux: "WHY LUX BRASIL?",
    exclusive_detail: "Exclusivity in Every Detail",
    cta_title: "Ready to change your luck?",
    cta_subtitle: "Join thousands of winners today.",
    cta_btn: "SPIN WHEEL NOW",

    feature_1_title: "Immediate Access",
    feature_1_desc: "Register and start spinning the wheel immediately to win prizes.",
    feature_2_title: "Verified Draws",
    feature_2_desc: "Our algorithms ensure total transparency and security in every spin.",
    feature_3_title: "Global Security",
    feature_3_desc: "Fully compliant with international data protection standards.",
    footer_desc: "The leading premium rewards platform. Transforming luck into unforgettable experiences with security and transparency.",
    footer_contact: "CONTACT & SUPPORT",
    footer_address_label: "CORPORATE ADDRESS",
    footer_rights: "All rights reserved.",
    footer_legal_title: "LEGAL & COMPLIANCE",
    legal_privacy: "Privacy Policy",
    legal_terms: "Terms of Use",
    legal_data: "GDPR & Data Protection",
    legal_rules: "Challenge Rules",
    developed_by: "Developed with Lux Secure™ Technology",

    // Roulette & Game
    prizes_title: "My Wallet & Prizes",
    prizes_empty: "You don't have prizes yet. Spin the wheel!",
    spin_btn: "SPIN NOW",
    spinning: "SPINNING...",
    congrats: "Congratulations!",
    try_again_title: "Not this time...",
    try_again_desc: "Don't give up, luck favors the persistent!",
    try_again_cashback_title: "CONSOLATION PRIZE",
    try_again_cashback_desc: "You received +{amount} LuxCoins in your wallet!",
    you_won: "You won",
    no_spins_title: "NO SPINS AVAILABLE",
    no_spins_desc: "You used all your daily spins. Complete missions to earn more right now!",
    btn_go_challenges: "GO TO MISSIONS",
    next_spin_label: "NEXT FREE SPIN",
    recent_activity: "Recent Activity",
    no_activity: "No recent activity.",
    your_spins: "YOUR SPINS",
    available: "AVAILABLE",
    next_refill_in: "NEXT REFILL IN",
    ready_to_use: "You have spins ready to use!",
    go_to_roulette: "GO TO WHEEL",
    redeem_now: "REDEEM NOW",
    add_wallet: "Add to Wallet",
    consolation_prize: "CONSOLATION PRIZE",
    you_won_label: "YOU WON",
    balance_updated: "Balance updated in your wallet.",
    close_and_continue: "CLOSE AND CONTINUE",
    label_code: "CODE:",
    msg_redemption_sent: "Request sent. Our concierge will contact you.",

    // Vault / Store
    vault_title: "The Vault",
    vault_subtitle: "Exchange your LuxCoins for extra spins and perks.",
    vault_exchange_success: "Exchange successful! +1 Spin.",
    vault_exchange_error: "Insufficient balance or exchange error.",
    exchange_rate: "100 LC = 1 SPIN",
    btn_exchange: "EXCHANGE NOW",
    extra_spin: "Extra Spin",
    cost_label: "COST",
    btn_redeem_item: "REDEEM ITEM",
    label_virtual: "VIRTUAL",
    label_physical: "PHYSICAL",
    label_money: "CASH",
    store_item_spin_name: "Extra Spin",
    store_item_spin_desc: "Exchange your coins for a new chance at the wheel.",
    store_item_headphone_name: "Headphone Lux Edition",
    store_item_headphone_desc: "Bluetooth Headphone FOO36-BRA. High fidelity sound.",
    store_item_earbuds_name: "Earbuds TWS Pro",
    store_item_earbuds_desc: "True Wireless Earbuds FOO42-BRA. Noise cancelling.",
    store_item_money_name: "Cash Prize",
    store_item_money_desc: "Redeem R$ {amount} directly to your account. Processing within 24h.",
    purchase_success: "Purchase successful! Item \"{item}\" added to your Wallet.",
    purchase_money_success: "Redemption of R${amount} requested! Check your Wallet.",

    // Challenges
    challenges_area: "OPERATIONAL AREA",
    challenges_title: "Mission Control",
    challenges_subtitle: "Complete exclusive contracts, level up and unlock rewards.",
    tab_daily: "DAILY OPS",
    tab_weekly: "WEEKLY",
    tab_monthly: "MONTHLY",
    tab_career: "CAREER",
    diff_easy: "ROOKIE",
    diff_medium: "VETERAN",
    diff_hard: "ELITE",
    progress: "PROGRESS",
    reward_label: "REWARD",
    btn_completed: "COMPLETED",
    btn_redeem_reward: "REDEEM",
    btn_proof: "PROVE IT",
    btn_in_progress: "IN PROGRESS",
    proof_dialog_title: "SEND PROOF",
    proof_dialog_desc: "Insert link or description of the task performed for manual validation.",
    btn_send_analysis: "SEND FOR ANALYSIS",
    reward_xp: "XP",
    visit_and_validate: "VISIT AND VALIDATE",
    verifying_access: "VERIFYING ACCESS...",
    access_validated: "Access validated! Reward credited.",
    proof_sent: "Proof sent for analysis!",

    // Dashboard & Level
    level_silver: "SILVER",
    level_gold: "GOLD",
    level_platinum: "PLATINUM",
    level_label: "LEVEL {level}",
    next_level: "Next level: {xp} XP",
    notification_missions_approved: "You have {count} approved missions! Redeem your prizes now.",
    notification_mission_completed: "Mission Completed: {name}! Reward delivered.",

    // Invite System
    invite_program_vip: "VIP PROGRAM",
    invite_premium: "Premium Referral",
    invite_active: "Active",
    invite_desc: "Invite your friends and receive {bonus} for each confirmed registration. The more friends, the more chances to win!",
    invite_bonus_highlight: "+1 free spin",
    invite_stats_friends: "Friends",
    invite_stats_spins: "Spins",
    invite_stats_rate: "Rate",
    invite_link_title: "Your Exclusive Link",
    invite_recent_list: "Recent Referrals",
    invite_share_text: "Come spin the wheel and win amazing prizes at Lux Brasil!",
    status_confirmed: "Bonus Paid",
    status_registered: "Registration Validated",
    status_rewarded: "Bonus Received",
    status_pending_invite: "Pending",

    // Admin
    admin_panel: "CONTROL PANEL",
    admin_title: "ADMINISTRATION",
    btn_update: "Update",
    tab_users: "USERS",
    tab_config: "WHEEL CONFIG",
    tab_audit: "AUDIT",
    search_placeholder: "Search by name, email or CPF...",
    total_label: "Total",
    table_user: "USER",
    table_cpf: "CPF",
    table_balance: "BALANCE / SPINS",
    table_ip: "IP ADDRESS",
    table_actions: "ACTIONS",
    status_banned: "BANNED",
    status_active: "ACTIVE",
    new_prize: "NEW PRIZE",
    prize_active: "Active on Wheel",
    btn_save: "SAVE",
    btn_cancel: "CANCEL",
    lbl_prob: "Probability (0-1)",
    lbl_color: "Color (Hex)",
    lbl_prize_name: "Prize Name",
    admin_add_coins: "Add LuxCoins",
    admin_add_spins: "Add Spins",
    admin_coins_amount: "Amount of Coins",
    admin_preset_loss: "Not this time",
    admin_preset_gold: "Gold",
    admin_preset_silver: "Silver",
    admin_central_requests: "Redemption Center",
    filter_pending: "Pending",
    filter_paid: "Paid",
    header_date: "DATE",
    header_user: "USER",
    header_prize: "PRIZE",
    header_code: "CODE",
    header_status: "STATUS",
    header_action: "ACTIONS",
    type_physical: "Physical",
    type_money: "Cash/LC",
    type_spins: "Spins",
    btn_pay: "Pay",
    btn_refuse: "Refuse",
    btn_reopen: "Reopen",
    empty_requests: "No pending requests.",
    empty_history: "No history found.",
    stats_total_users: "TOTAL USERS",
    stats_coins_circulation: "COINS IN CIRCULATION",
    stats_banned_users: "BANNED USERS",
    tip_prize_active: "Tip: If a prize has already been won, you cannot delete it. In this case, disable the 'Active on Wheel' option.",
    config_roulette: "Wheel Configuration",
    audit_report: "Activity Report",
    audit_subtitle: "Complete log of administrative actions",
    log_action_update_prize: "Update Prize",
    log_action_create_prize: "Create Prize",
    log_action_delete_prize: "Delete Prize",
    log_action_ban_user: "Ban User",
    log_action_unban_user: "Unban User",
    log_action_add_spins: "Credit Spins",
    log_action_add_coins: "Credit LuxCoins",
    log_action_ban_ip: "Block IP",
    log_action_update_redemption: "Redemption Status",
    dialog_add_spins_title: "Add Spins",
    dialog_add_coins_title: "Add LuxCoins",
    table_date: "DATE",
    table_prize: "PRIZE",
    table_code: "CODE",
    table_status: "STATUS",
    table_action: "ACTION",

    // Auth & Errors
    push_title: "Lux Brasil",
    push_body_spin: "Your daily spin is available!",
    register_title: "Create Account",
    name_label: "Full Name",
    cpf_label: "CPF",
    phone_label: "Phone",
    invite_label: "Invite Code (Optional)",
    pass_label: "Password",
    confirm_pass_label: "Confirm Password",
    already_member: "Already a member?",
    not_member: "Not a member yet?",
    forgot_pass: "Forgot password?",
    create_account_btn: "CREATE ACCOUNT & SPIN",
    register_success_check_email: "Account created! Check your email.",
    err_req: "Required field",
    err_cpf: "Invalid CPF",
    err_pass_match: "Passwords do not match",
    err_invite: "Invalid invite code",
    auth_email_confirm: "Your email has not been confirmed yet.",
    auth_invalid_creds: "Incorrect email or password.",

    // Legal
    legal_doc_official: "OFFICIAL LEGAL DOCUMENT",
    legal_updated: "Last updated: {date}",
  },

  zh: {
    // General
    loading: "加载中...",
    error_generic: "发生错误。请重试。",
    success: "成功！",
    close: "关闭",
    btn_close: "关闭",
    cancel: "取消",
    confirm: "确认",
    save: "保存",
    copy: "复制",
    copied: "已复制",
    view_all: "查看完整历史",

    // Navigation
    home: "首页",
    dashboard: "大厅",
    myPrizes: "钱包",
    vault: "Lux 商店",
    admin: "管理",
    logout: "退出",
    login: "登录",
    getStarted: "注册",
    spin: "幸运转盘",
    spinsAvailable: "次旋转",
    challenge: "挑战",
    challenges_tab: "任务",
    redeem: "兑换",
    wallet: "余额",
    open_wallet: "打开钱包",
    menu: "菜单",
    language_label: "语言",
    lux_coins: "Lux币",
    nav_balance: "金币",
    nav_profile: "个人资料",

    // Status
    status_pending: "可用",
    status_requested: "审核中",
    status_redeemed: "已支付/已发送",
    status_label: "状态",
    status_active_user: "活跃会员",
    member_area: "会员专区",

    // Hero & Landing
    heroTitle: "旋转并赢取",
    heroSubtitle: "在我们的平台上，您可以立即旋转并赢取奖品，加入我们。",
    landing_badge: "是时候赢取奖品了",
    landing_desc: "奢华抽奖的终极体验。注册，旋转专属转盘，并在完全安全的情况下立即赢取实物奖品。",
    btn_already_member: "已经是会员",
    stats_active_members: "活跃会员",
    stats_prizes_paid: "已付奖品",
    stats_secure: "安全与审计",
    why_lux: "为什么选择 LUX BRASIL？",
    exclusive_detail: "每一个细节都独一无二",
    cta_title: "准备好改变运气了吗？",
    cta_subtitle: "立即加入成千上万的赢家行列。",
    cta_btn: "立即旋转转盘",

    feature_1_title: "立即访问",
    feature_1_desc: "注册并立即开始旋转转盘以赢取奖品。",
    feature_2_title: "经过验证的抽奖",
    feature_2_desc: "我们的算法确保每次旋转都完全透明和安全。",
    feature_3_title: "全球安全",
    feature_3_desc: "完全符合国际数据保护标准。",
    footer_desc: "领先的高级奖励平台。以安全和透明的方式将运气转化为难忘的体验。",
    footer_contact: "联系与支持",
    footer_address_label: "公司地址",
    footer_rights: "版权所有。",
    footer_legal_title: "法律与合规",
    legal_privacy: "隐私政策",
    legal_terms: "使用条款",
    legal_data: "GDPR 和数据保护",
    legal_rules: "挑战规则",
    developed_by: "由 Lux Secure™ 技术开发",

    // Roulette & Game
    prizes_title: "我的钱包与奖品",
    prizes_empty: "您还没有奖品。旋转转盘！",
    spin_btn: "立即旋转",
    spinning: "旋转中...",
    congrats: "恭喜！",
    try_again_title: "这次没有中奖...",
    try_again_desc: "不要气馁，运气眷顾坚持者！",
    try_again_cashback_title: "安慰奖",
    try_again_cashback_desc: "您的钱包收到了 +{amount} Lux币！",
    you_won: "您赢了",
    no_spins_title: "没有可用旋转",
    no_spins_desc: "您已用完所有每日旋转次数。立即完成任务以赢取更多！",
    btn_go_challenges: "前往任务",
    next_spin_label: "下次免费旋转",
    recent_activity: "近期活动",
    no_activity: "无近期活动",
    your_spins: "您的旋转",
    available: "可用",
    next_refill_in: "下次补充时间",
    ready_to_use: "您有可用的旋转！",
    go_to_roulette: "前往转盘",
    redeem_now: "立即兑换",
    add_wallet: "添加到钱包",
    consolation_prize: "安慰奖",
    you_won_label: "您赢得了",
    balance_updated: "钱包余额已更新。",
    close_and_continue: "关闭并继续",
    label_code: "代码：",
    msg_redemption_sent: "请求已发送。我们的礼宾人员将与您联系。",

    // Vault / Store
    vault_title: "金库",
    vault_subtitle: "用您的 Lux币兑换额外的旋转和福利。",
    vault_exchange_success: "兑换成功！+1次旋转。",
    vault_exchange_error: "余额不足或兑换错误。",
    exchange_rate: "100 LC = 1次旋转",
    btn_exchange: "立即兑换",
    extra_spin: "额外旋转",
    cost_label: "费用",
    btn_redeem_item: "兑换物品",
    label_virtual: "虚拟",
    label_physical: "实物",
    label_money: "现金",
    store_item_spin_name: "额外旋转",
    store_item_spin_desc: "用您的金币兑换一次新的转盘机会。",
    store_item_headphone_name: "耳机 Lux 版",
    store_item_headphone_desc: "蓝牙耳机 FOO36-BRA。高保真音质。",
    store_item_earbuds_name: "耳机 TWS Pro",
    store_item_earbuds_desc: "真无线耳机 FOO42-BRA。降噪。",
    store_item_money_name: "现金奖",
    store_item_money_desc: "直接兑换 R$ {amount} 到您的账户。24小时内处理。",
    purchase_success: "购买成功！物品 \"{item}\" 已添加到您的钱包。",
    purchase_money_success: "申请兑换 R${amount}！请检查您的钱包。",

    // Challenges
    challenges_area: "操作区",
    challenges_title: "任务控制中心",
    challenges_subtitle: "完成独家合同，升级并解锁奖励。",
    tab_daily: "日常行动",
    tab_weekly: "每周",
    tab_monthly: "每月",
    tab_career: "职业生涯",
    diff_easy: "新手",
    diff_medium: "老手",
    diff_hard: "精英",
    progress: "进度",
    reward_label: "奖励",
    btn_completed: "已完成",
    btn_redeem_reward: "兑换",
    btn_proof: "证明",
    btn_in_progress: "进行中",
    proof_dialog_title: "发送证明",
    proof_dialog_desc: "插入执行任务的链接或描述以进行人工验证。",
    btn_send_analysis: "发送分析",
    reward_xp: "经验值",
    visit_and_validate: "访问并验证",
    verifying_access: "正在验证访问...",
    access_validated: "访问已验证！奖励已发放。",
    proof_sent: "证明已发送进行分析！",

    // Dashboard & Level
    level_silver: "白银",
    level_gold: "黄金",
    level_platinum: "铂金",
    level_label: "等级 {level}",
    next_level: "下一级：{xp} XP",
    notification_missions_approved: "您有 {count} 个已批准的任务！立即兑换您的奖品。",
    notification_mission_completed: "任务完成：{name}！奖励已发放。",

    // Invite System
    invite_program_vip: "VIP 计划",
    invite_premium: "高级推荐",
    invite_active: "活跃",
    invite_desc: "邀请您的朋友，每确认一个注册即可获得 {bonus}。朋友越多，获胜机会越大！",
    invite_bonus_highlight: "+1次免费旋转",
    invite_stats_friends: "朋友",
    invite_stats_spins: "旋转",
    invite_stats_rate: "比率",
    invite_link_title: "您的专属链接",
    invite_recent_list: "近期推荐",
    invite_share_text: "来 Lux Brasil 旋转转盘并赢取惊人奖品！",
    status_confirmed: "奖金已付",
    status_registered: "注册已验证",
    status_rewarded: "奖金已收",
    status_pending_invite: "待定",

    // Admin
    admin_panel: "控制面板",
    admin_title: "管理",
    btn_update: "更新",
    tab_users: "用户",
    tab_config: "转盘配置",
    tab_audit: "审计",
    search_placeholder: "按姓名、邮箱或 CPF 搜索...",
    total_label: "总计",
    table_user: "用户",
    table_cpf: "CPF",
    table_balance: "余额 / 旋转",
    table_ip: "IP 地址",
    table_actions: "操作",
    status_banned: "已封禁",
    status_active: "活跃",
    new_prize: "新奖品",
    prize_active: "在转盘上激活",
    btn_save: "保存",
    btn_cancel: "取消",
    lbl_prob: "概率 (0-1)",
    lbl_color: "颜色 (Hex)",
    lbl_prize_name: "奖品名称",
    admin_add_coins: "添加 Lux币",
    admin_add_spins: "添加旋转",
    admin_coins_amount: "金币数量",
    admin_preset_loss: "这次没有",
    admin_preset_gold: "黄金",
    admin_preset_silver: "白银",
    admin_central_requests: "兑换中心",
    filter_pending: "待定",
    filter_paid: "已付",
    header_date: "日期",
    header_user: "用户",
    header_prize: "奖品",
    header_code: "代码",
    header_status: "状态",
    header_action: "操作",
    type_physical: "实物",
    type_money: "现金/LC",
    type_spins: "旋转",
    btn_pay: "支付",
    btn_refuse: "拒绝",
    btn_reopen: "重新打开",
    empty_requests: "没有待处理的请求。",
    empty_history: "未找到历史记录。",
    stats_total_users: "用户总数",
    stats_coins_circulation: "流通金币",
    stats_banned_users: "被封禁用户",
    tip_prize_active: "提示：如果奖品已经被赢取，您无法删除它。在这种情况下，请禁用“在转盘上激活”选项。",
    config_roulette: "转盘配置",
    audit_report: "活动报告",
    audit_subtitle: "管理操作的完整日志",
    log_action_update_prize: "更新奖品",
    log_action_create_prize: "创建奖品",
    log_action_delete_prize: "删除奖品",
    log_action_ban_user: "封禁用户",
    log_action_unban_user: "解封用户",
    log_action_add_spins: "记入旋转",
    log_action_add_coins: "记入 Lux币",
    log_action_ban_ip: "封锁 IP",
    log_action_update_redemption: "兑换状态",
    dialog_add_spins_title: "添加旋转",
    dialog_add_coins_title: "添加 Lux币",
    table_date: "日期",
    table_prize: "奖品",
    table_code: "代码",
    table_status: "状态",
    table_action: "操作",

    // Auth & Errors
    push_title: "Lux Brasil",
    push_body_spin: "您的每日旋转已可用！",
    register_title: "创建账户",
    name_label: "全名",
    cpf_label: "CPF",
    phone_label: "手机",
    invite_label: "邀请码（可选）",
    pass_label: "密码",
    confirm_pass_label: "确认密码",
    already_member: "已经是会员？",
    not_member: "还不是会员？",
    forgot_pass: "忘记密码？",
    create_account_btn: "创建账户并旋转",
    register_success_check_email: "账户已创建！请检查您的邮箱。",
    err_req: "必填字段",
    err_cpf: "无效的 CPF",
    err_pass_match: "密码不匹配",
    err_invite: "无效的邀请码",
    auth_email_confirm: "您的邮箱尚未确认。",
    auth_invalid_creds: "邮箱或密码错误。",

    // Legal
    legal_doc_official: "官方法律文件",
    legal_updated: "最后更新：{date}",
  }
};
