import { createTheme } from '@mui/material';
import { Translations } from './types';

export const APP_NAME = "Lux Brasil";
export const COMPANY_INFO = {
  name: "BRAILLUX ENTERTAINMENT LTDA",
  fantasy_name: "BRAILLUX ENTERTAINMENT",
  cnpj: "61.197.797/0001-53",
  address: "R. Gentil Moreno, 618 - Conj. Hab. Antonio Pedro Ortolan, Sertãozinho - SP, 14.177-255",
  email: "suporte@braillux.com",
  phone: "(16) 98810-3754",
  dpo: "privacidade@braillux.com"
};

// Lux Casino Dark Theme
export const theme = createTheme({
  palette: {
    mode: 'dark',
    primary: {
      main: '#D4AF37', // Metallic Gold
      dark: '#AA8C2C',
      light: '#F3E5AB',
      contrastText: '#000000',
    },
    secondary: {
      main: '#800020', // Burgundy
    },
    background: {
      default: '#050510',
      paper: '#0F121D',   
    },
    text: {
      primary: '#F5F5F5',
      secondary: '#A0A0A0',
    },
    divider: 'rgba(212, 175, 55, 0.2)',
  },
  typography: {
    fontFamily: '"Inter", "Roboto", sans-serif',
    h1: { fontFamily: '"Montserrat", sans-serif', fontWeight: 800, letterSpacing: '-0.02em', textTransform: 'uppercase' },
    h2: { fontFamily: '"Montserrat", sans-serif', fontWeight: 700, letterSpacing: '-0.01em' },
    h3: { fontFamily: '"Montserrat", sans-serif', fontWeight: 700, color: '#D4AF37' },
    h4: { fontFamily: '"Montserrat", sans-serif', fontWeight: 600 },
    h5: { fontFamily: '"Montserrat", sans-serif', fontWeight: 600 },
    h6: { fontFamily: '"Montserrat", sans-serif', fontWeight: 600 },
    button: { fontFamily: '"Montserrat", sans-serif', fontWeight: 700, letterSpacing: 1 },
    overline: { fontFamily: '"Inter", sans-serif', letterSpacing: 2, fontWeight: 600 },
  },
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          borderRadius: 4, 
          padding: '12px 32px',
          textTransform: 'none',
          fontSize: '1rem',
        },
        containedPrimary: {
          background: 'linear-gradient(135deg, #D4AF37 0%, #AA8C2C 100%)',
          color: '#000',
          boxShadow: '0 4px 20px rgba(212, 175, 55, 0.2)',
          animation: 'pulse-gold 2s infinite', 
          '&:hover': {
            background: 'linear-gradient(135deg, #F3E5AB 0%, #D4AF37 100%)',
          },
        },
        outlined: {
            borderWidth: '1px',
            borderColor: '#D4AF37',
            color: '#D4AF37',
        }
      },
    },
    MuiPaper: {
      styleOverrides: {
        root: {
          backgroundImage: 'none',
          backgroundColor: '#0F121D',
          color: '#F5F5F5',
          borderRadius: 12,
          border: '1px solid rgba(255, 255, 255, 0.05)',
        },
      },
    },
    MuiChip: {
      styleOverrides: {
        root: {
          fontWeight: 600,
        }
      }
    }
  },
});

export const TRANSLATIONS: Translations = {
  pt: {
    home: "Início",
    dashboard: "Lobby",
    myPrizes: "Minha Carteira",
    admin: "Administração",
    logout: "Sair",
    login: "Entrar",
    getStarted: "Criar Conta",
    spin: "Roleta Premiada",
    spinsAvailable: "Giros",
    challenge: "Desafios",
    challenges_tab: "Missões",
    redeem: "Resgatar",
    wallet: "Saldo",
    menu: "MENU",
    language_label: "Idioma",
    
    status_pending: "Disponível",
    status_requested: "Em Análise",
    status_redeemed: "Pago/Enviado",
    status_label: "Status",
    status_active_user: "Membro Ativo",
    member_area: "ÁREA DE MEMBROS",
    
    heroTitle: "GIRE E GANHE",
    heroSubtitle: "Aqui na nossa plataforma você pode girar e ganhar na mesma hora, venha fazer parte.",
    feature_1_title: "Acesso Imediato",
    feature_1_desc: "Cadastre-se e comece a girar a roleta imediatamente para ganhar prêmios.",
    feature_2_title: "Sorteios Verificados",
    feature_2_desc: "Nossos algoritmos garantem total transparência e segurança em cada giro.",
    feature_3_title: "Segurança Global",
    feature_3_desc: "Totalmente compatível com padrões internacionais de proteção de dados.",

    footer_rights: "Todos os direitos reservados.",
    footer_legal: "Sorteios auditados. Jogue com responsabilidade.",
    
    prizes_title: "Minha Carteira & Prêmios",
    prizes_empty: "Você ainda não possui prêmios. Gire a roleta!",
    spin_btn: "GIRAR AGORA",
    spinning: "SORTEANDO...",
    congrats: "Parabéns!",
    you_won: "Você ganhou",
    add_wallet: "Adicionar à Carteira",
    open_wallet: "Abrir Minha Carteira",
    next_spin_label: "PRÓXIMO GIRO GRÁTIS",
    recent_activity: "Atividade Recente",
    
    your_spins: "SEUS GIROS",
    available: "DISPONÍVEIS",
    next_refill_in: "PRÓXIMO REFILL EM",
    ready_to_use: "Você tem giros prontos para usar!",
    go_to_roulette: "IR PARA ROLETA",
    redeem_now: "RESGATAR AGORA",

    challenges_area: "ÁREA OPERACIONAL",
    challenges_title: "Central de Missões",
    challenges_subtitle: "Complete contratos exclusivos, suba de nível e desbloqueie recompensas.",
    tab_daily: "OPERAÇÕES DIÁRIAS",
    tab_weekly: "SEMANAIS",
    tab_monthly: "MENSAIS",
    tab_career: "CARREIRA",
    diff_easy: "INICIANTE",
    diff_medium: "VETERANO",
    diff_hard: "ELITE",
    progress: "PROGRESSO",
    reward_label: "RECOMPENSA",
    btn_completed: "CONCLUÍDO",
    btn_redeem_reward: "RESGATAR",
    btn_proof: "COMPROVAR",
    btn_in_progress: "EM ANDAMENTO",
    proof_dialog_title: "ENVIAR COMPROVANTE",
    proof_dialog_desc: "Insira o link ou descrição da tarefa realizada para validação manual.",
    btn_cancel: "CANCELAR",
    btn_send_analysis: "ENVIAR PARA ANÁLISE",

    admin_panel: "PAINEL DE CONTROLE",
    admin_title: "ADMINISTRAÇÃO",
    btn_update: "Atualizar",
    tab_users: "USUÁRIOS",
    tab_config: "CONFIG. ROLETA",
    tab_audit: "AUDITORIA",
    search_placeholder: "Buscar por nome, email ou CPF...",
    total_label: "Total",
    table_user: "USUÁRIO",
    table_cpf: "CPF",
    table_balance: "SALDO / GIROS",
    table_ip: "IP ADDRESS",
    table_actions: "AÇÕES",
    status_banned: "BANIDO",
    status_active: "ATIVO",
    new_prize: "NOVO PRÊMIO",
    prize_active: "Ativo na Roleta",
    btn_save: "SALVAR",
    
    push_title: "Lux Brasil",
    push_body_spin: "Seu giro diário já está disponível!",
    cooldown_msg: "Próximo giro grátis em",
    
    register_title: "Crie sua Conta",
    register_subtitle: "Preencha seus dados para começar a ganhar.",
    name_label: "Nome Completo",
    cpf_label: "CPF",
    phone_label: "Celular",
    invite_label: "Código de Convite (Opcional)",
    pass_label: "Senha",
    confirm_pass_label: "Confirmar Senha",
    already_member: "Já é membro?",
    not_member: "Ainda não é membro?",
    forgot_pass: "Esqueceu a senha?",
    create_account_btn: "CRIAR CONTA E GIRAR",
    register_success_check_email: "Conta criada! Verifique seu e-mail.",
    
    err_req: "Campo obrigatório",
    err_cpf: "CPF inválido",
    err_pass_match: "As senhas não conferem",
    err_invite: "Código de convite inválido",

    admin_users: "Usuários",
    admin_config: "Config. Roleta",
    admin_audit: "Logs de Auditoria",
    admin_manage_users: "Gerenciamento de Usuários",
    save_changes: "Salvar Alterações",
    lbl_active: "Ativo",
    lbl_color: "Cor",
    lbl_prob: "Probabilidade",
    lbl_prize_name: "Nome do Prêmio",
    
    // Navbar specific
    nav_balance: "SALDO",
    nav_profile: "PERFIL",

    // Table Headers (My Prizes)
    table_date: "DATA",
    table_prize: "PRÊMIO",
    table_code: "CÓDIGO",
    table_status: "STATUS",
    table_action: "AÇÃO",
    table_time: "HORA",
    loading: "Carregando..."
  },
  en: {
    home: "Home",
    dashboard: "Lobby",
    myPrizes: "Wallet & Prizes",
    admin: "Admin",
    logout: "Logout",
    login: "Login",
    getStarted: "Join Now",
    spin: "Prize Wheel",
    spinsAvailable: "Spins",
    challenge: "Challenges",
    challenges_tab: "Missions",
    redeem: "Redeem",
    wallet: "Balance",
    menu: "MENU",
    language_label: "Language",
    
    status_pending: "Available",
    status_requested: "Processing",
    status_redeemed: "Paid/Sent",
    status_label: "Status",
    status_active_user: "Active Member",
    member_area: "MEMBER AREA",
    
    heroTitle: "SPIN & WIN",
    heroSubtitle: "Here on our platform you can spin and win instantly. Come join us.",
    feature_1_title: "Instant Access",
    feature_1_desc: "Sign up and start spinning the wheel immediately to win prizes.",
    feature_2_title: "Verified Draws",
    feature_2_desc: "Our algorithms ensure absolute transparency and security in every spin.",
    feature_3_title: "Global Security",
    feature_3_desc: "Fully compliant with international data protection standards.",

    footer_rights: "All rights reserved.",
    footer_legal: "Audited draws. Play responsibly.",
    
    prizes_title: "My Wallet & Prizes",
    prizes_empty: "No prizes yet. Spin the wheel!",
    spin_btn: "SPIN NOW",
    spinning: "SPINNING...",
    congrats: "Congratulations!",
    you_won: "You won",
    add_wallet: "Add to Wallet",
    open_wallet: "Open My Wallet",
    next_spin_label: "NEXT FREE SPIN",
    recent_activity: "Recent Activity",

    your_spins: "YOUR SPINS",
    available: "AVAILABLE",
    next_refill_in: "NEXT REFILL IN",
    ready_to_use: "You have spins ready to use!",
    go_to_roulette: "GO TO ROULETTE",
    redeem_now: "CLAIM NOW",

    challenges_area: "OPERATIONAL AREA",
    challenges_title: "Mission Control",
    challenges_subtitle: "Complete exclusive contracts, level up, and unlock rewards.",
    tab_daily: "DAILY OPS",
    tab_weekly: "WEEKLY",
    tab_monthly: "MONTHLY",
    tab_career: "CAREER",
    diff_easy: "ROOKIE",
    diff_medium: "VETERAN",
    diff_hard: "ELITE",
    progress: "PROGRESS",
    reward_label: "REWARD",
    btn_completed: "COMPLETED",
    btn_redeem_reward: "CLAIM",
    btn_proof: "SUBMIT PROOF",
    btn_in_progress: "IN PROGRESS",
    proof_dialog_title: "SUBMIT PROOF",
    proof_dialog_desc: "Enter the link or description of the task performed for manual validation.",
    btn_cancel: "CANCEL",
    btn_send_analysis: "SEND FOR REVIEW",

    admin_panel: "CONTROL PANEL",
    admin_title: "ADMINISTRATION",
    btn_update: "Refresh",
    tab_users: "USERS",
    tab_config: "WHEEL CONFIG",
    tab_audit: "AUDIT",
    search_placeholder: "Search by name, email or ID...",
    total_label: "Total",
    table_user: "USER",
    table_cpf: "ID DOC",
    table_balance: "BALANCE / SPINS",
    table_ip: "IP ADDRESS",
    table_actions: "ACTIONS",
    status_banned: "BANNED",
    status_active: "ACTIVE",
    new_prize: "NEW PRIZE",
    prize_active: "Active on Wheel",
    btn_save: "SAVE",

    table_date: "DATE",
    table_prize: "PRIZE",
    table_code: "CODE",
    table_status: "STATUS",
    table_action: "ACTION",
    table_time: "TIME",
    loading: "Loading...",
    
    push_title: "Lux Brasil",
    push_body_spin: "Your daily spin is ready!",
    cooldown_msg: "Next free spin in",
    
    register_title: "Create Account",
    register_subtitle: "Fill in your details to start winning.",
    name_label: "Full Name",
    cpf_label: "National ID (CPF)",
    phone_label: "Mobile Phone",
    invite_label: "Invite Code (Optional)",
    pass_label: "Password",
    confirm_pass_label: "Confirm Password",
    already_member: "Already a member?",
    not_member: "Not a member yet?",
    forgot_pass: "Forgot password?",
    create_account_btn: "CREATE ACCOUNT & SPIN",
    register_success_check_email: "Account created! Please check your email.",

    err_req: "Required field",
    err_cpf: "Invalid ID",
    err_pass_match: "Passwords do not match",
    err_invite: "Invalid invite code",

    admin_users: "Users",
    admin_config: "Roulette Config",
    admin_audit: "Audit Logs",
    admin_manage_users: "User Management",
    save_changes: "Save Changes",
    lbl_active: "Active",
    lbl_color: "Color",
    lbl_prob: "Probability",
    lbl_prize_name: "Prize Name",
    nav_balance: "BALANCE",
    nav_profile: "PROFILE"
  },
  zh: {
    home: "首页",
    dashboard: "大厅",
    myPrizes: "钱包",
    admin: "管理",
    logout: "登出",
    login: "登录",
    getStarted: "开始",
    spin: "奖品轮盘",
    spinsAvailable: "旋转",
    challenge: "挑战",
    challenges_tab: "任务",
    redeem: "兑换",
    wallet: "余额",
    menu: "菜单",
    language_label: "语言",
    
    status_pending: "可用",
    status_requested: "处理中",
    status_redeemed: "已支付",
    status_label: "状态",
    status_active_user: "活跃会员",
    member_area: "会员区",
    
    heroTitle: "旋转并赢取",
    heroSubtitle: "在我们的平台上，您可以立即旋转并赢取奖品。加入我们。",
    feature_1_title: "即时访问",
    feature_1_desc: "注册并立即开始旋转轮盘以赢取奖品。",
    feature_2_title: "验证抽奖",
    feature_2_desc: "我们的算法确保每次旋转的绝对透明和安全。",
    feature_3_title: "全球安全",
    feature_3_desc: "完全符合国际数据保护标准。",
    
    footer_rights: "版权所有。",
    footer_legal: "审计抽奖。理性游戏。",
    
    prizes_title: "我的钱包与奖品",
    prizes_empty: "暂无奖品。旋转轮盘！",
    spin_btn: "立即旋转",
    spinning: "旋转中...",
    congrats: "恭喜！",
    you_won: "你赢了",
    add_wallet: "存入钱包",
    open_wallet: "打开钱包",
    next_spin_label: "下次免费旋转",
    recent_activity: "近期活动",

    your_spins: "您的旋转",
    available: "可用",
    next_refill_in: "下次补充于",
    ready_to_use: "您有可用的旋转！",
    go_to_roulette: "前往轮盘",
    redeem_now: "立即领取",

    challenges_area: "操作区",
    challenges_title: "任务中心",
    challenges_subtitle: "完成独家合同，升级并解锁奖励。",
    tab_daily: "日常行动",
    tab_weekly: "每周",
    tab_monthly: "每月",
    tab_career: "职业生涯",
    diff_easy: "新手",
    diff_medium: "老兵",
    diff_hard: "精英",
    progress: "进度",
    reward_label: "奖励",
    btn_completed: "已完成",
    btn_redeem_reward: "领取",
    btn_proof: "提交证明",
    btn_in_progress: "进行中",
    proof_dialog_title: "提交证明",
    proof_dialog_desc: "输入任务链接或描述以供人工审核。",
    btn_cancel: "取消",
    btn_send_analysis: "提交审核",

    admin_panel: "控制面板",
    admin_title: "管理",
    btn_update: "刷新",
    tab_users: "用户",
    tab_config: "轮盘配置",
    tab_audit: "审计",
    search_placeholder: "搜索姓名，邮箱或ID...",
    total_label: "总计",
    table_user: "用户",
    table_cpf: "证件号",
    table_balance: "余额 / 旋转",
    table_ip: "IP地址",
    table_actions: "操作",
    status_banned: "已封禁",
    status_active: "活跃",
    new_prize: "新奖品",
    prize_active: "轮盘激活",
    btn_save: "保存",

    table_date: "日期",
    table_prize: "奖品",
    table_code: "代码",
    table_status: "状态",
    table_action: "操作",
    table_time: "时间",
    loading: "加载中...",
    
    push_title: "Lux Brasil",
    push_body_spin: "您的每日旋转已准备就绪！",
    cooldown_msg: "下次免费旋转",
    
    register_title: "创建账户",
    register_subtitle: "填写您的详细信息以开始赢取。",
    name_label: "全名",
    cpf_label: "身份证 (CPF)",
    phone_label: "手机",
    invite_label: "邀请码 (可选)",
    pass_label: "密码",
    confirm_pass_label: "确认密码",
    already_member: "已经是会员？",
    not_member: "还没注册？",
    forgot_pass: "忘记密码？",
    create_account_btn: "创建账户并旋转",
    register_success_check_email: "账户已创建！请检查您的电子邮件。",

    err_req: "必填项",
    err_cpf: "无效身份证",
    err_pass_match: "密码不匹配",
    err_invite: "无效邀请码",

    admin_users: "用户",
    admin_config: "轮盘配置",
    admin_audit: "审计日志",
    admin_manage_users: "用户管理",
    save_changes: "保存更改",
    lbl_active: "激活",
    lbl_color: "颜色",
    lbl_prob: "概率",
    lbl_prize_name: "奖品名称",
    nav_balance: "余额",
    nav_profile: "概况"
  }
};