
import { createTheme } from '@mui/material/styles';
import { Translations } from './types';

export const APP_NAME = "Lux Brasil";
export const APP_VERSION = "1.2.4"; 
export const BASE_URL = 'https://roletalux.com.br';
export const SPIN_DURATION_MS = 6000;
export const XP_PER_LEVEL = 1000;

export const COMPANY_INFO = {
  name: "BRASILUX ENTERTAINMENT LTDA",
  fantasy_name: "BRASILUX ENTERTAINMENT",
  cnpj: "61.197.797/0001-53",
  address: "R. Gentil Moreno, 618 - Conj. Hab. Antonio Pedro Ortolan, Sertãozinho - SP, 14.177-255",
  email: "suporte@braillux.com",
  phone: "+55 16 99424-4231",
  dpo: "privacidade@braillux.com"
};

// Coleção de Avatares expandida com múltiplos estilos
export const AVATAR_STYLES: Record<string, { style: string; seeds: string[] }> = {
  '3D Style': {
    style: 'adventurer',
    seeds: [
      'king-lux', 'queen-lux', 'investor', 'player-one', 
      'high-roller', 'lucky-star', 'gold-miner', 'cyber-punk', 
      'gentleman', 'lady-luck', 'mafia-boss', 'secret-agent',
      'crypto-king', 'influencer', 'artist', 'dj-lux',
    ]
  },
  'Robôs': {
    style: 'bottts-neutral',
    seeds: [
      'robo-one', 'cyborg-seven', 'mech-unit', 'data-bot',
      'protocol-droid', 'sentry-bot', 'lux-bot', 'gold-plated',
      'voltaic', 'gearhead'
    ]
  },
  'Pixel Art': {
    style: 'pixel-art',
    seeds: [
      'retro-gamer', 'pixel-king', '8-bit-hero', 'arcade-master',
      'glitch-lord', 'vixel', 'dot-matrix', 'sprite-champ',
      'rek-it', 'pac-man-ghost'
    ]
  }
};


// Lux Casino Dark Theme
export const theme = createTheme({
  palette: {
    mode: 'dark',
    primary: {
      main: '#D4AF37', // Metallic Gold
      dark: '#AA8C2C',
      light: '#F3E5AB',
      contrastText: '#000000',
    },
    secondary: {
      main: '#800020', // Burgundy
    },
    background: {
      default: '#050510',
      paper: '#0F121D',   
    },
    text: {
      primary: '#F5F5F5',
      secondary: '#A0A0A0',
    },
    divider: 'rgba(212, 175, 55, 0.2)',
  },
  typography: {
    fontFamily: '"Inter", "Roboto", sans-serif',
    h1: { fontFamily: '"Montserrat", sans-serif', fontWeight: 800, letterSpacing: '-0.02em', textTransform: 'uppercase' },
    h2: { fontFamily: '"Montserrat", sans-serif', fontWeight: 700, letterSpacing: '-0.01em' },
    h3: { fontFamily: '"Montserrat", sans-serif', fontWeight: 700, color: '#D4AF37' },
    h4: { fontFamily: '"Montserrat", sans-serif', fontWeight: 600 },
    h5: { fontFamily: '"Montserrat", sans-serif', fontWeight: 600 },
    h6: { fontFamily: '"Montserrat", sans-serif', fontWeight: 600 },
    button: { fontFamily: '"Montserrat", sans-serif', fontWeight: 700, letterSpacing: 1 },
    overline: { fontFamily: '"Inter", sans-serif', letterSpacing: 2, fontWeight: 600 },
  },
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          borderRadius: 4, 
          padding: '12px 32px',
          textTransform: 'none',
          fontSize: '1rem',
        },
        containedPrimary: {
          background: 'linear-gradient(135deg, #D4AF37 0%, #AA8C2C 100%)',
          color: '#000',
          boxShadow: '0 4px 20px rgba(212, 175, 55, 0.2)',
          animation: 'pulse-gold 2s infinite', 
          '&:hover': {
            background: 'linear-gradient(135deg, #F3E5AB 0%, #D4AF37 100%)',
          },
        },
        outlined: {
            borderWidth: '1px',
            borderColor: '#D4AF37',
            color: '#D4AF37',
        }
      },
    },
    MuiPaper: {
      styleOverrides: {
        root: {
          backgroundImage: 'none',
          backgroundColor: '#0F121D',
          color: '#F5F5F5',
          borderRadius: 12,
          border: '1px solid rgba(255, 255, 255, 0.05)',
        },
      },
    },
    MuiChip: {
      styleOverrides: {
        root: {
          fontWeight: 600,
        }
      }
    }
  },
});

export const TRANSLATIONS: Translations = {
  pt: {
    loading: "Carregando...",
    error_generic: "Ocorreu um erro. Tente novamente.",
    success: "Sucesso!",
    close: "Fechar",
    btn_close: "FECHAR",
    cancel: "Cancelar",
    confirm: "Confirmar",
    save: "Salvar Alterações",
    copy: "Copiar",
    copied: "Copiado",
    view_all: "VER HISTÓRICO COMPLETO",
    home: "Início",
    dashboard: "Lobby",
    myPrizes: "Minha Carteira",
    vault: "Loja Lux",
    admin: "Administração",
    logout: "Sair",
    login: "Entrar",
    getStarted: "Criar Conta",
    spin: "Roleta Premiada",
    spinsAvailable: "Giros",
    challenge: "Ranking",
    challenges_tab: "Ranking VIP",
    redeem: "Resgatar",
    wallet: "Saldo",
    open_wallet: "ABRIR CARTEIRA",
    menu: "MENU",
    language_label: "Idioma",
    lux_coins: "LuxCoins",
    nav_balance: "COINS",
    nav_profile: "PERFIL",
    edit_profile: "Editar Perfil",
    my_account: "Minha Conta",
    profile_updated: "Perfil atualizado com sucesso.",
    status_pending: "Disponível",
    status_requested: "Em Análise",
    status_redeemed: "Pago/Enviado",
    status_label: "Status",
    status_active_user: "Membro Ativo",
    member_area: "ÁREA DE MEMBROS",
    ranking_title: "Ranking de Indicações",
    ranking_subtitle: "Os maiores influenciadores do mês disputando o pódio de ouro.",
    ranking_ends: "ENCERRA EM:",
    your_rank: "SUA POSIÇÃO",
    invites_valid: "CONVITES VÁLIDOS",
    top_1_prize: "R$ 1000 + 10 Giros",
    top_2_prize: "R$ 120 + 5 Giros",
    top_3_prize: "R$ 50 + 1 Giro",
    top_50_prize: "5 Giros Extras",
    challenges_area: "COMPETIÇÃO ELITE",
    proof_dialog_title: "ENVIAR COMPROVANTE",
    btn_send_analysis: "ENVIAR",
    tab_daily: "DIÁRIO",
    level_label: "NÍVEL {level}",
    invite_program_vip: "PROGRAMA VIP",
    invite_premium: "Indicação Premium",
    invite_active: "Ativo",
    invite_desc: "Convide amigos e ganhe {bonus} por cada um que confirmar o cadastro. Mais amigos, mais prêmios!",
    invite_bonus_highlight: "+1 Giro, +75 LC & +100 XP",
    invite_stats_total: "Total Convidados",
    invite_stats_spins_earned: "Giros Ganhos",
    invite_stats_lc_earned: "LuxCoins Ganhos",
    invite_link_title: "Seu Link de Convite",
    invite_manager_title: "Gerenciador de Convites",
    invite_guest_label: "Convidado",
    invite_date_label: "Data do Convite",
    invite_status_label: "Status",
    invite_reward_label: "Recompensa",
    status_pending_confirmation: "Aguardando Confirmação",
    status_confirmed_paid: "Confirmado e Pago",
    invite_no_referrals: "Você ainda não convidou ninguém. Compartilhe seu link e comece a ganhar!",
    invite_share_text: "Seu amigo {name} te convidou para a Lux Brasil! 💎✨ Cadastre-se com o código dele e comece com um giro grátis. Venha ganhar prêmios incríveis!",
    status_confirmed: "Bônus Pago",
    status_registered: "Cadastro Validado",
    status_rewarded: "Bônus Recebido",
    status_pending_invite: "Aguardando",
    admin_panel: "PAINEL DE CONTROLE",
    admin_title: "ADMINISTRAÇÃO",
    btn_update: "Atualizar",
    tab_users: "USUÁRIOS",
    tab_config: "CONFIG. ROLETA",
    tab_audit: "AUDITORIA",
    tab_validate: "VALIDAR MISSÕES",
    search_placeholder: "Buscar por nome, email ou CPF...",
    total_label: "Total",
    table_user: "USUÁRIO",
    table_cpf: "CPF",
    table_balance: "SALDO / GIROS",
    table_ip: "IP ADDRESS",
    table_actions: "AÇÕES",
    status_banned: "BANIDO",
    status_active: "ATIVO",
    new_prize: "NOVO PRÊMIO",
    prize_active: "Ativo na Roleta",
    btn_save: "SALVAR",
    btn_cancel: "CANCELAR",
    lbl_prob: "Probabilidade (0-1)",
    lbl_color: "Cor (Hex)",
    lbl_prize_name: "Nome do Prêmio",
    admin_add_coins: "Adicionar LuxCoins",
    admin_add_spins: "Adicionar Giros",
    admin_coins_amount: "Quantidade de Coins",
    admin_preset_loss: "Não foi dessa vez",
    admin_preset_gold: "Gold",
    admin_preset_silver: "Silver",
    admin_central_requests: "Central de Resgates",
    filter_pending: "Pendentes",
    filter_paid: "Pagos",
    header_date: "DATA",
    header_user: "USUÁRIO",
    header_prize: "PRÊMIO",
    header_code: "CÓDIGO",
    header_status: "STATUS",
    header_action: "AÇÕES",
    type_physical: "Físico",
    type_money: "Dinheiro/LC",
    type_spins: "Giros",
    btn_pay: "Pagar",
    btn_refuse: "Recusar",
    btn_reopen: "Reabrir",
    empty_requests: "Nenhuma solicitação pendente.",
    empty_history: "Nenhum histórico encontrado.",
    stats_total_users: "TOTAL USUÁRIOS",
    stats_coins_circulation: "COINS EM CIRCULAÇÃO",
    stats_banned_users: "USUÁRIOS BANIDOS",
    tip_prize_active: "Dica: Se um prêmio já saiu na roleta, você não conseguirá excluí-lo. Nesse caso, desative a opção 'Ativo na Roleta'.",
    config_roulette: "Configuração da Roleta",
    audit_report: "Relatório de Atividades",
    audit_subtitle: "Registro completo de ações administrativas",
    log_action_update_prize: "Edição de Prêmio",
    log_action_create_prize: "Criação de Prêmio",
    log_action_delete_prize: "Exclusão de Prêmio",
    log_action_ban_user: "Banimento de Usuário",
    log_action_unban_user: "Desbloqueio de Usuário",
    log_action_add_spins: "Crédito de Giros",
    log_action_add_coins: "Crédito de LuxCoins",
    log_action_ban_ip: "Bloqueio de IP",
    log_action_update_redemption: "Status de Solicitação",
    dialog_add_spins_title: "Adicionar Giros",
    dialog_add_coins_title: "Adicionar LuxCoins",
    table_date: "DATA",
    table_prize: "PRÊMIO",
    table_code: "CÓDIGO",
    table_status: "STATUS",
    table_action: "AÇÃO",
    admin_msg_approved: "Aprovado!",
    admin_msg_rejected: "Rejeitado.",
    admin_msg_added_spins: "Adicionado {amount} giros",
    admin_msg_added_coins: "Adicionado {amount} coins",
    admin_msg_ban_confirm: "Tem certeza que deseja {action} {name}?",
    admin_msg_ban: "BANIR",
    admin_msg_unban: "DESBANIR",
    admin_msg_ip_ban: "Bloquear IP {ip}?",
    admin_msg_prize_created: "Prêmio criado!",
    admin_msg_prize_delete_confirm: "Excluir prêmio?",
    admin_msg_confirm_payment: "Confirmar pagamento?",
    admin_msg_refuse_request: "Recusar solicitação?",
    btn_approve: "Aprovar & Pagar",
    btn_reject: "Rejeitar",
    table_mission: "Missão",
    table_proof: "Prova",
    link_view_proof: "Ver Prova",
    empty_proofs: "Nenhuma prova pendente.",
    btn_edit_user: "Editar Usuário",
    btn_print_labels: "IMPRIMIR ETIQUETAS",
    push_title: "Lux Brasil",
    push_body_spin: "Seu giro diário já está disponível!",
    register_title: "Crie sua Conta",
    name_label: "Nome Completo",
    cpf_label: "CPF",
    phone_label: "Celular",
    invite_label: "Código de Convite (Opcional)",
    pass_label: "Senha",
    confirm_pass_label: "Confirmar Senha",
    already_member: "Já é membro?",
    not_member: "Ainda não é membro?",
    forgot_pass: "Esqueceu a senha?",
    create_account_btn: "CRIAR CONTA E GIRAR",
    register_success_check_email: "Conta criada! Verifique seu e-mail.",
    err_req: "Campo obrigatório",
    err_cpf: "CPF inválido",
    err_pass_match: "As senhas não conferem",
    err_invite: "Código de convite inválido",
    auth_email_confirm: "Seu e-mail ainda não foi confirmado.",
    auth_invalid_creds: "E-mail ou senha incorretos.",
    legal_doc_official: "DOCUMENTO LEGAL OFICIAL",
    legal_updated: "Última atualização: {date}",
    admin_print_title: "Etiquetas - Lux Brasil",
    btn_print: "🖨️ IMPRIMIR",
    label_prize: "PRÊMIO:",
    label_code_short: "Cód:",
    label_tel: "TEL:",
    proof_analysis_title: "Análise de Comprovante",
    proof_context_label: "Contexto / Mensagem:",
    proof_visual_label: "Comprovante Visual:",
    proof_open_original: "Abrir Original",
    proof_no_image: "Nenhuma imagem anexada. (Prova antiga ou apenas texto)",
    btn_visiting: "VERIFICANDO...",
    btn_sending: "ENVIANDO...",
    upload_click_label: "Clique para selecionar Imagem",
    upload_required: "* Obrigatório",
    admin_override_title: "Admin Override",
    profile_avatar_edit: "Alterar Avatar",
    profile_info_edit: "Informações Pessoais",
    choose_avatar: "ESCOLHA SEU AVATAR",
    joined_date: "MEMBRO DESDE",
    footer_desc: "A experiência definitiva em sorteios de luxo. Cadastre-se, gire a roleta exclusiva e conquiste prêmios reais.",
    footer_contact: "Contato & Suporte",
    footer_address_label: "ENDEREÇO COMERCIAL:",
    footer_legal_title: "Documentos Legais",
    legal_privacy: "Política de Privacidade",
    legal_terms: "Termos de Uso",
    legal_data: "Política de Dados",
    legal_rules: "Regras da Competição",
    footer_rights: "Todos os direitos reservados.",
    developed_by: "Desenvolvido com precisão e luxo.",
    spinning: "GIRANDO...",
    spin_btn: "GIRAR",
    level_silver: "PRATA",
    level_gold: "OURO",
    level_platinum: "PLATINA",
    next_level: "{xp} XP para o próximo nível",
    recent_activity: "Atividade Recente",
    no_activity: "Nenhuma atividade ainda.",
    notification_missions_approved: "Você tem {count} missões aprovadas para resgatar!",
    notification_mission_completed: "Missão Concluída: {name}!",
    your_spins: "Seus Giros",
    available: "Disponível",
    next_refill_in: "Próximo Giro Grátis em",
    redeem_now: "RESGATAR AGORA",
    ready_to_use: "Você tem giros disponíveis para usar!",
    go_to_roulette: "IR PARA A ROLETA",
    try_again_title: "Não foi desta vez",
    consolation_prize: "Prêmio de Consolação",
    congrats: "Parabéns, você ganhou!",
    you_won_label: "Você ganhou",
    balance_updated: "Seu saldo foi atualizado.",
    close_and_continue: "FECHAR E CONTINUAR",
    no_spins_title: "Giros Esgotados",
    no_spins_desc: "Você não tem giros disponíveis. Complete missões ou aguarde o próximo giro diário para continuar.",
    btn_go_challenges: "VER MISSÕES",
    prizes_title: "Meus Prêmios",
    prizes_empty: "Você ainda não ganhou nenhum prêmio.",
    label_code: "CÓDIGO",
    msg_redemption_sent: "Solicitação de resgate enviada! Acompanhe o status.",
    cost_label: "Custo",
    btn_redeem_item: "Trocar Coins",
    vault_title: "Loja de Vantagens",
    vault_subtitle: "Use seus LuxCoins para resgatar prêmios exclusivos ou mais giros.",
    vault_exchange_success: "Troca realizada! Seus giros foram adicionados.",
    vault_exchange_error: "Erro na troca. Verifique seu saldo e tente novamente.",
    purchase_success: "Resgate de {item} realizado! Verifique sua carteira.",
    purchase_money_success: "Resgate de R$ {amount} realizado! Verifique sua carteira.",
    store_item_spin_name: "Pacote de 1 Giro Extra",
    store_item_spin_desc: "A sorte está ao seu lado? Adquira mais uma chance de girar a roleta.",
    label_virtual: "Virtual",
    store_item_headphone_name: "Headphone Premium",
    store_item_headphone_desc: "Qualidade de som de estúdio para sua imersão total.",
    label_physical: "Físico",
    store_item_earbuds_name: "Fones de Ouvido Sem Fio",
    store_item_earbuds_desc: "Liberdade e som cristalino para o seu dia a dia.",
    store_item_money_name: "Crédito de R$ 1000,00",
    store_item_money_desc: "Resgate R$ {amount} em créditos para usar como quiser.",
    label_money: "Dinheiro",
    landing_hero_tag: "CHEGOU SUA HORA DE GANHAR",
    powered_by: "POWERED BY",
    landing_hero_title_1: "GIRE E",
    landing_hero_title_2: "GANHE",
    landing_hero_subtitle: "A experiência definitiva em sorteios de luxo. Cadastre-se, gire a roleta exclusiva e conquiste prêmios reais instantaneamente com total segurança.",
    landing_create_account: "CRIAR CONTA",
    landing_already_member: "JÁ SOU MEMBRO",
    landing_stat_members: "MEMBROS ATIVOS",
    landing_stat_prizes: "PRÊMIOS PAGOS",
    landing_stat_secure: "SEGURO & AUDITADO",
    landing_why_title: "POR QUE A LUX BRASIL?",
    landing_why_subtitle: "Exclusividade em",
    landing_why_subtitle_highlight: "Cada Detalhe",
    landing_feature1_title: "Acesso Imediato",
    landing_feature1_desc: "Sem espera. Cadastre-se e receba seu primeiro giro gratuito instantaneamente para começar a ganhar.",
    landing_feature2_title: "Prêmios",
    landing_feature2_desc: "De experiências gastronômicas a produtos exclusivos, ou LuxCoins. Escolha sem erro.",
    landing_feature3_title: "Segurança de Elite",
    landing_feature3_desc: "Seus dados são criptografados. Nossos algoritmos de sorteio são transparentes e auditáveis.",
    landing_cta_title: "Pronto para a sua sorte mudar?",
    landing_cta_subtitle: "Junte-se a milhares de vencedores hoje mesmo.",
    landing_cta_button: "GIRAR ROLETA AGORA",
    login_welcome_back: "BEM-VINDO DE VOLTA",
    login_err_permission: "Erro de permissão. Contate o administrador.",
    login_err_connection: "Erro interno de conexão. Tente atualizar a página.",
    login_err_conflict: "Ocorreu um conflito ao criar sua conta. Tente fazer login ou contate o suporte.",
    auth_err_unknown: "Erro desconhecido na autenticação.",
    err_name_short: "Nome muito curto",
    err_name_full: "Digite seu nome completo (Nome e Sobrenome)",
    err_cpf_format: "Formato de CPF inválido",
    err_phone_short: "Telefone incompleto",
    err_phone_invalid: "Telefone inválido",
    err_email_invalid: "Email inválido",
    err_pass_short: "Mínimo 6 caracteres",
    err_create_account: "Erro ao criar conta. Tente novamente.",
    err_ip_limit_exceeded: "IP excedeu o limite de contas. Contate o suporte.",
    register_success_title: "Verifique seu E-mail",
    register_success_body: "Enviamos um link de confirmação exclusivo para o seu endereço.",
    register_success_warn_title: "Atenção:",
    register_success_warn_body: "Procure por um e-mail da LUX BRASIL. Se não encontrar, verifique sua caixa de Spam ou Lixo Eletrônico.",
    register_back_to_login: "Voltar para Login",
    dashboard_greeting: "Olá, {name}!",
    dashboard_subtitle: "Sua jornada de prêmios continua aqui.",
    dashboard_vip_panel: "PAINEL VIP",
    dashboard_level: "NÍVEL",
    dashboard_xp_total: "XP TOTAL",
    dashboard_prize_log: "Log de Prêmios",
    admin_roulette_subtitle: "Gerencie os itens, probabilidades e pesos.",
    admin_edit_prize: "Editar Prêmio",
    admin_prob_hint: "Probabilidade (0.1 = 1%, 1.0 = 10%)",
    admin_type_label: "Tipo",
    admin_value_label: "Valor (Qtd)",
    admin_image_url_label: "URL da Imagem",
    admin_description_label: "Descrição",
    admin_prize_updated: "Prêmio atualizado!",
    admin_contact_whatsapp: "Contatar no WhatsApp",
    admin_contact_btn: "Contato",
    rarity_legendary: "LEGENDÁRIO",
    rarity_epic: "ÉPICO",
    rarity_rare: "RARO",
    rarity_common: "COMUM",
    audit_target: "Alvo",
    audit_details: "Detalhes",
    admin_ip_banned: "IP Banido.",
    admin_challenge: "Desafio",
    admin_download_image: "Baixar Imagem",
    admin_processing: "Processando...",
    admin_tab_themes: "EVENTOS / TEMAS",
    admin_themes_title: "Configuração de Temas & Eventos",
    admin_maintenance_title: "MODO MANUTENÇÃO (Sistema)",
    admin_maintenance_desc: "Ative esta opção para bloquear o acesso de usuários comuns. Apenas administradores conseguirão acessar a plataforma através da rota de login secreta na tela de manutenção.",
    admin_maintenance_active: "⚠️ MANUTENÇÃO ATIVA",
    admin_system_online: "Sistema Online",
    admin_theme_active: "Tema Ativo",
    admin_theme_inactive: "Tema Desativado",
    admin_select_theme: "Selecione o Tema",
    theme_default: "Padrão (Nenhum)",
    theme_carnival: "Carnaval (Confete + Roxo/Verde)",
    theme_custom: "Customizado (Script/CSS)",
    admin_save_config: "Salvar Configuração",
    admin_config_saved: "Configuração do sistema salva e aplicada com sucesso!",
    admin_config_error: "Erro ao salvar configuração: {error}",
    admin_amount_label: "Quantidade",
    invite_competition: "Competição",
    invite_performance: "Performance",
    invite_friends_unit: "amigos",
    invite_new_player: "Novo Jogador",
    invite_vip_access: "Seu Acesso VIP",
    invite_share_to_earn: "Compartilhe para ganhar recompensas.",
    invite_total_earnings: "Ganhos Totais",
    invite_your_achievements: "Suas Conquistas",
    xp_label: "XP",
    invite_effectiveness: "Eficácia",
    invite_confirmation_rate: "Taxa de Confirmação",
    invite_of_invites: "dos convites",
    maintenance_title: "Estamos Polindo os Diamantes",
    maintenance_subtitle: "Nossa equipe está realizando melhorias exclusivas para garantir que sua experiência seja ainda mais brilhante e segura.",
    maintenance_status: "STATUS: ATUALIZAÇÃO BLINDADA",
    maintenance_back_soon: "Voltaremos em instantes.",
    maintenance_staff_access: "Área Restrita / Staff Access",
    support_title: "Suporte Lux",
    support_greeting: "Olá! Sou a Natália. Clique para atendimento.",
    support_tooltip_benefits: "Benefícios Diários 🎁",
    support_tooltip_vip: "Grupo VIP Telegram 💎",
    support_tooltip_charity: "Ação Beneficente ❤️",
    support_tooltip_benefits_short: "Benefícios",
    support_tooltip_vip_short: "VIP",
    support_tooltip_charity_short: "Beneficente",
    progression_title: "Jornada de Prestígio",
    progression_subtitle: "Sua evolução no universo Lux desbloqueia vantagens exclusivas.",
    tier_bronze: "Bronze",
    tier_gold: "Ouro",
    tier_platinum: "Platina",
    tier_master: "Mestre Lux",
    level_perks: "Vantagens do Patamar",
    level_perks_by_tier: "Vantagens por Patamar",
    perk_levelup_reward: "Recompensa de 50 LC a cada nível.",
    perk_bronze_consolation: "Compensação de 10 LC em giros não premiados.",
    perk_gold_consolation: "Compensação de 15 LC em giros não premiados.",
    perk_platinum_consolation: "Compensação de 20 LC em giros não premiados.",
    perk_master_consolation: "Compensação de 30 LC em giros não premiados.",
    perk_master_xp_boost: "Bônus de 50 XP por giro na roleta.",
    you_are_here: "Você está aqui",
    badges_title: "Insígnias Conquistadas",
    no_badges: "Continue sua jornada para desbloquear insígnias raras.",
    badge_master_roulette_name: "Mestre da Roleta",
    badge_master_roulette_desc: "Concedida aos membros de elite que alcançaram o nível máximo da plataforma.",
    xp_for_next_level: "XP para o próximo nível",
    
    // Novas traduções de IP
    IP_LIMIT_REACHED: 'Limite de cadastros atingido para este endereço IP. Entre em contato com o suporte.',
    IP_MISSING: 'Não foi possível identificar seu endereço IP. Verifique sua conexão.',
    err_ip_blocked: 'Este IP foi bloqueado por excesso de tentativas de cadastro.',
    err_email_exists: 'Este e-mail já está cadastrado',
    err_cpf_exists: 'Este CPF já está cadastrado',
    err_phone_exists: 'Este telefone já está cadastrado',
    err_duplicate_data: 'Dados duplicados encontrados',
    err_check_data: 'Erro ao validar dados. Tente novamente.',
    err_signup_failed: 'Falha no cadastro. Tente novamente.'
  },
  en: {
    loading: "Loading...",
    error_generic: "An error occurred. Please try again.",
    success: "Success!",
    close: "Close",
    btn_close: "CLOSE",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save Changes",
    copy: "Copy",
    copied: "Copied",
    view_all: "VIEW FULL HISTORY",
    home: "Home",
    dashboard: "Lobby",
    myPrizes: "My Wallet",
    vault: "Lux Store",
    admin: "Admin",
    logout: "Log Out",
    login: "Login",
    getStarted: "Sign Up",
    spin: "Prize Wheel",
    spinsAvailable: "Spins",
    challenge: "Ranking",
    challenges_tab: "VIP Ranking",
    redeem: "Redeem",
    wallet: "Balance",
    open_wallet: "OPEN WALLET",
    menu: "MENU",
    language_label: "Language",
    lux_coins: "LuxCoins",
    nav_balance: "COINS",
    nav_profile: "PROFILE",
    edit_profile: "Edit Profile",
    my_account: "My Account",
    profile_updated: "Profile updated successfully.",
    status_pending: "Available",
    status_requested: "In Review",
    status_redeemed: "Paid/Sent",
    status_label: "Status",
    status_active_user: "Active Member",
    member_area: "MEMBER AREA",
    ranking_title: "Referral Ranking",
    ranking_subtitle: "The biggest influencers of the month competing for the gold podium.",
    ranking_ends: "ENDS IN:",
    your_rank: "YOUR RANK",
    invites_valid: "VALID INVITES",
    top_1_prize: "R$ 1000 + 10 Spins",
    top_2_prize: "$120 + 5 Spins",
    top_3_prize: "$50 + 1 Spin",
    top_50_prize: "5 Extra Spins",
    challenges_area: "ELITE COMPETITION",
    proof_dialog_title: "SUBMIT PROOF",
    btn_send_analysis: "SEND",
    tab_daily: "DAILY",
    level_label: "LEVEL {level}",
    invite_program_vip: "VIP PROGRAM",
    invite_premium: "Premium Referral",
    invite_active: "Active",
    invite_desc: "Invite friends and earn {bonus} for each confirmed sign-up. More friends, more prizes!",
    invite_bonus_highlight: "+1 Spin, +75 LC & +100 XP",
    invite_stats_total: "Total Invited",
    invite_stats_spins_earned: "Spins Earned",
    invite_stats_lc_earned: "LuxCoins Earned",
    invite_link_title: "Your Invite Link",
    invite_manager_title: "Invite Manager",
    invite_guest_label: "Guest",
    invite_date_label: "Invite Date",
    invite_status_label: "Status",
    invite_reward_label: "Reward",
    status_pending_confirmation: "Awaiting Confirmation",
    status_confirmed_paid: "Confirmed and Paid",
    invite_no_referrals: "You haven't invited anyone yet. Share your link and start earning!",
    invite_share_text: "Your friend {name} has invited you to Lux Brasil! 💎✨ Sign up with their code and start with a free spin. Come win amazing prizes!",
    status_confirmed: "Bonus Paid",
    status_registered: "Registration Validated",
    status_rewarded: "Bonus Received",
    status_pending_invite: "Pending",
    admin_panel: "CONTROL PANEL",
    admin_title: "ADMINISTRATION",
    btn_update: "Refresh",
    tab_users: "USERS",
    tab_config: "WHEEL CONFIG",
    tab_audit: "AUDIT LOG",
    tab_validate: "VALIDATE MISSIONS",
    search_placeholder: "Search by name, email, or CPF...",
    total_label: "Total",
    table_user: "USER",
    table_cpf: "CPF",
    table_balance: "BALANCE / SPINS",
    table_ip: "IP ADDRESS",
    table_actions: "ACTIONS",
    status_banned: "BANNED",
    status_active: "ACTIVE",
    new_prize: "NEW PRIZE",
    prize_active: "Active on Wheel",
    btn_save: "SAVE",
    btn_cancel: "CANCEL",
    lbl_prob: "Probability (0-1)",
    lbl_color: "Color (Hex)",
    lbl_prize_name: "Prize Name",
    admin_add_coins: "Add LuxCoins",
    admin_add_spins: "Add Spins",
    admin_coins_amount: "Amount of Coins",
    admin_preset_loss: "Not this time",
    admin_preset_gold: "Gold",
    admin_preset_silver: "Silver",
    admin_central_requests: "Redemption Center",
    filter_pending: "Pending",
    filter_paid: "Paid",
    header_date: "DATE",
    header_user: "USER",
    header_prize: "PRIZE",
    header_code: "CODE",
    header_status: "STATUS",
    header_action: "ACTIONS",
    type_physical: "Physical",
    type_money: "Cash/LC",
    type_spins: "Spins",
    btn_pay: "Pay",
    btn_refuse: "Refuse",
    btn_reopen: "Reopen",
    empty_requests: "No pending requests.",
    empty_history: "No history found.",
    stats_total_users: "TOTAL USERS",
    stats_coins_circulation: "COINS IN CIRCULATION",
    stats_banned_users: "BANNED USERS",
    tip_prize_active: "Tip: If a prize has already been won, you can't delete it. Instead, disable the 'Active on Wheel' option.",
    config_roulette: "Wheel Configuration",
    audit_report: "Activity Report",
    audit_subtitle: "Complete log of administrative actions",
    log_action_update_prize: "Prize Edit",
    log_action_create_prize: "Prize Creation",
    log_action_delete_prize: "Prize Deletion",
    log_action_ban_user: "User Ban",
    log_action_unban_user: "User Unban",
    log_action_add_spins: "Spins Credit",
    log_action_add_coins: "LuxCoins Credit",
    log_action_ban_ip: "IP Ban",
    log_action_update_redemption: "Request Status",
    dialog_add_spins_title: "Add Spins",
    dialog_add_coins_title: "Add LuxCoins",
    table_date: "DATE",
    table_prize: "PRIZE",
    table_code: "CODE",
    table_status: "STATUS",
    table_action: "ACTION",
    admin_msg_approved: "Approved!",
    admin_msg_rejected: "Rejected.",
    admin_msg_added_spins: "Added {amount} spins",
    admin_msg_added_coins: "Added {amount} coins",
    admin_msg_ban_confirm: "Are you sure you want to {action} {name}?",
    admin_msg_ban: "BAN",
    admin_msg_unban: "UNBAN",
    admin_msg_ip_ban: "Block IP {ip}?",
    admin_msg_prize_created: "Prize created!",
    admin_msg_prize_delete_confirm: "Delete prize?",
    admin_msg_confirm_payment: "Confirm payment?",
    admin_msg_refuse_request: "Refuse request?",
    btn_approve: "Approve & Pay",
    btn_reject: "Reject",
    table_mission: "Mission",
    table_proof: "Proof",
    link_view_proof: "View Proof",
    empty_proofs: "No pending proofs.",
    btn_edit_user: "Edit User",
    btn_print_labels: "PRINT LABELS",
    push_title: "Lux Brasil",
    push_body_spin: "Your daily spin is now available!",
    register_title: "Create Account",
    name_label: "Full Name",
    cpf_label: "CPF",
    phone_label: "Mobile Phone",
    invite_label: "Invite Code (Optional)",
    pass_label: "Password",
    confirm_pass_label: "Confirm Password",
    already_member: "Already a member?",
    not_member: "Not a member yet?",
    forgot_pass: "Forgot password?",
    create_account_btn: "CREATE ACCOUNT & SPIN",
    register_success_check_email: "Account created! Check your email.",
    err_req: "Required field",
    err_cpf: "Invalid CPF",
    err_pass_match: "Passwords do not match",
    err_invite: "Invalid invite code",
    auth_email_confirm: "Your email has not been confirmed yet.",
    auth_invalid_creds: "Incorrect email or password.",
    legal_doc_official: "OFFICIAL LEGAL DOCUMENT",
    legal_updated: "Last updated: {date}",
    admin_print_title: "Labels - Lux Brasil",
    btn_print: "🖨️ PRINT",
    label_prize: "PRIZE:",
    label_code_short: "Code:",
    label_tel: "TEL:",
    proof_analysis_title: "Proof Analysis",
    proof_context_label: "Context / Message:",
    proof_visual_label: "Visual Proof:",
    proof_open_original: "Open Original",
    proof_no_image: "No image attached. (Old or text-only proof)",
    btn_visiting: "VERIFYING...",
    btn_sending: "SENDING...",
    upload_click_label: "Click to select Image",
    upload_required: "* Required",
    admin_override_title: "Admin Override",
    profile_avatar_edit: "Change Avatar",
    profile_info_edit: "Personal Information",
    choose_avatar: "CHOOSE YOUR AVATAR",
    joined_date: "MEMBER SINCE",
    footer_desc: "The definitive experience in luxury raffles. Sign up, spin the exclusive roulette and win real prizes.",
    footer_contact: "Contact & Support",
    footer_address_label: "BUSINESS ADDRESS:",
    footer_legal_title: "Legal Documents",
    legal_privacy: "Privacy Policy",
    legal_terms: "Terms of Use",
    legal_data: "Data Policy",
    legal_rules: "Competition Rules",
    footer_rights: "All rights reserved.",
    developed_by: "Developed with precision and luxury.",
    spinning: "SPINNING...",
    spin_btn: "SPIN",
    level_silver: "SILVER",
    level_gold: "GOLD",
    level_platinum: "PLATINUM",
    next_level: "{xp} XP to next level",
    recent_activity: "Recent Activity",
    no_activity: "No activity yet.",
    notification_missions_approved: "You have {count} approved missions to claim!",
    notification_mission_completed: "Mission Completed: {name}!",
    your_spins: "Your Spins",
    available: "Available",
    next_refill_in: "Next Free Spin in",
    redeem_now: "REDEEM NOW",
    ready_to_use: "You have spins available to use!",
    go_to_roulette: "GO TO ROULETTE",
    try_again_title: "Not this time",
    consolation_prize: "Consolation Prize",
    congrats: "Congratulations, you won!",
    you_won_label: "You won",
    balance_updated: "Your balance has been updated.",
    close_and_continue: "CLOSE AND CONTINUE",
    no_spins_title: "No Spins Left",
    no_spins_desc: "You have no spins available. Complete missions or wait for the next daily spin to continue.",
    btn_go_challenges: "VIEW MISSIONS",
    prizes_title: "My Prizes",
    prizes_empty: "You haven't won any prizes yet.",
    label_code: "CODE",
    msg_redemption_sent: "Redemption request sent! Track its status.",
    cost_label: "Cost",
    btn_redeem_item: "Exchange Coins",
    vault_title: "Perks Store",
    vault_subtitle: "Use your LuxCoins to redeem exclusive prizes or more spins.",
    vault_exchange_success: "Exchange successful! Your spins have been added.",
    vault_exchange_error: "Exchange error. Check your balance and try again.",
    purchase_success: "Redemption of {item} successful! Check your wallet.",
    purchase_money_success: "Redemption of R$ {amount} successful! Check your wallet.",
    store_item_spin_name: "1 Extra Spin Pack",
    store_item_spin_desc: "Is luck on your side? Get another chance to spin the wheel.",
    label_virtual: "Virtual",
    store_item_headphone_name: "Premium Headphones",
    store_item_headphone_desc: "Studio-quality sound for your total immersion.",
    label_physical: "Physical",
    store_item_earbuds_name: "Wireless Earbuds",
    store_item_earbuds_desc: "Freedom and crystal-clear sound for your daily life.",
    store_item_money_name: "R$ 1000.00 Credit",
    store_item_money_desc: "Redeem R$ {amount} in credits to use as you wish.",
    label_money: "Money",
    landing_hero_tag: "YOUR TIME TO WIN HAS COME",
    powered_by: "POWERED BY",
    landing_hero_title_1: "SPIN AND",
    landing_hero_title_2: "WIN",
    landing_hero_subtitle: "The definitive experience in luxury raffles. Sign up, spin the exclusive roulette, and win real prizes instantly with total security.",
    landing_create_account: "CREATE ACCOUNT",
    landing_already_member: "ALREADY A MEMBER",
    landing_stat_members: "ACTIVE MEMBERS",
    landing_stat_prizes: "PRIZES PAID",
    landing_stat_secure: "SECURE & AUDITED",
    landing_why_title: "WHY LUX BRASIL?",
    landing_why_subtitle: "Exclusivity in",
    landing_why_subtitle_highlight: "Every Detail",
    landing_feature1_title: "Immediate Access",
    landing_feature1_desc: "No waiting. Sign up and get your first free spin instantly to start winning.",
    landing_feature2_title: "Prizes",
    landing_feature2_desc: "From dining experiences to exclusive products, or LuxCoins. Choose without mistake.",
    landing_feature3_title: "Elite Security",
    landing_feature3_desc: "Your data is encrypted. Our raffle algorithms are transparent and auditable.",
    landing_cta_title: "Ready for your luck to change?",
    landing_cta_subtitle: "Join thousands of winners today.",
    landing_cta_button: "SPIN THE WHEEL NOW",
    login_welcome_back: "WELCOME BACK",
    login_err_permission: "Permission error. Contact administrator.",
    login_err_connection: "Internal connection error. Try refreshing the page.",
    login_err_conflict: "A conflict occurred while creating your account. Try logging in or contact support.",
    auth_err_unknown: "Unknown authentication error.",
    err_name_short: "Name too short",
    err_name_full: "Enter your full name (First and Last Name)",
    err_cpf_format: "Invalid CPF format",
    err_phone_short: "Incomplete phone number",
    err_phone_invalid: "Invalid phone number",
    err_email_invalid: "Invalid email",
    err_pass_short: "Minimum 6 characters",
    err_create_account: "Error creating account.",
    err_ip_limit_exceeded: "IP has exceeded the account limit. Please contact support.",
    register_success_title: "Check Your Email",
    register_success_body: "We've sent an exclusive confirmation link to your address.",
    register_success_warn_title: "Attention:",
    register_success_warn_body: "Look for an email from LUX BRASIL. If you can't find it, check your Spam or Junk folder.",
    register_back_to_login: "Back to Login",
    dashboard_greeting: "Hello, {name}!",
    dashboard_subtitle: "Your prize journey continues here.",
    dashboard_vip_panel: "VIP PANEL",
    dashboard_level: "LEVEL",
    dashboard_xp_total: "TOTAL XP",
    dashboard_prize_log: "Prize Log",
    admin_roulette_subtitle: "Manage items, probabilities, and weights.",
    admin_edit_prize: "Edit Prize",
    admin_prob_hint: "Probability (0.1 = 1%, 1.0 = 10%)",
    admin_type_label: "Type",
    admin_value_label: "Value (Qty)",
    admin_image_url_label: "Image URL",
    admin_description_label: "Description",
    admin_prize_updated: "Prize updated!",
    admin_contact_whatsapp: "Contact on WhatsApp",
    admin_contact_btn: "Contact",
    rarity_legendary: "LEGENDARY",
    rarity_epic: "EPIC",
    rarity_rare: "RARE",
    rarity_common: "COMMON",
    audit_target: "Target",
    audit_details: "Details",
    admin_ip_banned: "IP Banned.",
    admin_challenge: "Challenge",
    admin_download_image: "Download Image",
    admin_processing: "Processing...",
    admin_tab_themes: "EVENTS / THEMES",
    admin_themes_title: "Themes & Events Configuration",
    admin_maintenance_title: "MAINTENANCE MODE (System)",
    admin_maintenance_desc: "Enable this option to block access for regular users. Only administrators will be able to access the platform through the secret login route on the maintenance screen.",
    admin_maintenance_active: "⚠️ MAINTENANCE ACTIVE",
    admin_system_online: "System Online",
    admin_theme_active: "Theme Active",
    admin_theme_inactive: "Theme Inactive",
    admin_select_theme: "Select Theme",
    theme_default: "Default (None)",
    theme_carnival: "Carnival (Confetti + Purple/Green)",
    theme_custom: "Custom (Script/CSS)",
    admin_save_config: "Save Configuration",
    admin_config_saved: "System configuration saved and applied successfully!",
    admin_config_error: "Error saving configuration: {error}",
    admin_amount_label: "Amount",
    invite_competition: "Competition",
    invite_performance: "Performance",
    invite_friends_unit: "friends",
    invite_new_player: "New Player",
    invite_vip_access: "Your VIP Access",
    invite_share_to_earn: "Share to earn rewards.",
    invite_total_earnings: "Total Earnings",
    invite_your_achievements: "Your Achievements",
    xp_label: "XP",
    invite_effectiveness: "Effectiveness",
    invite_confirmation_rate: "Confirmation Rate",
    invite_of_invites: "of invites",
    maintenance_title: "We Are Polishing the Diamonds",
    maintenance_subtitle: "Our team is making exclusive improvements to ensure your experience is even brighter and more secure.",
    maintenance_status: "STATUS: ARMORED UPDATE",
    maintenance_back_soon: "We'll be back in a moment.",
    maintenance_staff_access: "Restricted Area / Staff Access",
    support_title: "Lux Support",
    support_greeting: "Hi! I'm Natália. Click for support.",
    support_tooltip_benefits: "Daily Benefits 🎁",
    support_tooltip_vip: "VIP Telegram Group 💎",
    support_tooltip_charity: "Charity Action ❤️",
    support_tooltip_benefits_short: "Benefits",
    support_tooltip_vip_short: "VIP",
    support_tooltip_charity_short: "Charity",
    progression_title: "Prestige Journey",
    progression_subtitle: "Your evolution in the Lux universe unlocks exclusive advantages.",
    tier_bronze: "Bronze",
    tier_gold: "Gold",
    tier_platinum: "Platinum",
    tier_master: "Master Lux",
    level_perks: "Tier Perks",
    level_perks_by_tier: "Perks by Tier",
    perk_levelup_reward: "Reward of 50 LC for each level up.",
    perk_bronze_consolation: "10 LC compensation on non-winning spins.",
    perk_gold_consolation: "15 LC compensation on non-winning spins.",
    perk_platinum_consolation: "20 LC compensation on non-winning spins.",
    perk_master_consolation: "30 LC compensation on non-winning spins.",
    perk_master_xp_boost: "50 XP bonus per spin on the roulette.",
    you_are_here: "You are here",
    badges_title: "Badges Earned",
    no_badges: "Continue your journey to unlock rare badges.",
    badge_master_roulette_name: "Master of the Roulette",
    badge_master_roulette_desc: "Awarded to elite members who have reached the platform's maximum level.",
    xp_for_next_level: "XP to next level",

    // New IP translations
    IP_LIMIT_REACHED: 'Registration limit reached for this IP address. Contact support.',
    IP_MISSING: 'Could not identify your IP address. Check your connection.',
    err_ip_blocked: 'This IP has been blocked due to excessive registration attempts.',
    err_email_exists: 'This email is already registered',
    err_cpf_exists: 'This CPF is already registered',
    err_phone_exists: 'This phone number is already registered',
    err_duplicate_data: 'Duplicate data found',
    err_check_data: 'Error validating data. Please try again.',
    err_signup_failed: 'Signup failed. Please try again.'
  },
  zh: {
    loading: "加载中...",
    error_generic: "发生错误。请再试一次。",
    success: "成功！",
    close: "关闭",
    btn_close: "关闭",
    cancel: "取消",
    confirm: "确认",
    save: "保存更改",
    copy: "复制",
    copied: "已复制",
    view_all: "查看完整历史",
    home: "首页",
    dashboard: "大厅",
    myPrizes: "我的钱包",
    vault: "Lux商店",
    admin: "管理",
    logout: "登出",
    login: "登录",
    getStarted: "注册",
    spin: "幸运轮盘",
    spinsAvailable: "旋转次数",
    challenge: "排名",
    challenges_tab: "VIP排名",
    redeem: "兑换",
    wallet: "余额",
    open_wallet: "打开钱包",
    menu: "菜单",
    language_label: "语言",
    lux_coins: "Lux金币",
    nav_balance: "金币",
    nav_profile: "个人资料",
    edit_profile: "编辑个人资料",
    my_account: "我的账户",
    profile_updated: "个人资料更新成功。",
    status_pending: "可用",
    status_requested: "审核中",
    status_redeemed: "已支付/已发送",
    status_label: "状态",
    status_active_user: "活跃会员",
    member_area: "会员区",
    ranking_title: "推荐排名",
    ranking_subtitle: "本月最具影响力的影响者正在争夺黄金领奖台。",
    ranking_ends: "结束于：",
    your_rank: "您的排名",
    invites_valid: "有效邀请",
    top_1_prize: "R$ 1000 + 10次旋转",
    top_2_prize: "¥120 + 5次旋转",
    top_3_prize: "¥50 + 1次旋转",
    top_50_prize: "5次额外旋转",
    challenges_area: "精英竞赛",
    proof_dialog_title: "提交证明",
    btn_send_analysis: "发送",
    tab_daily: "每日",
    level_label: "等级 {level}",
    invite_program_vip: "VIP计划",
    invite_premium: "高级推荐",
    invite_active: "活跃",
    invite_desc: "邀请朋友，每次确认注册即可获得{bonus}。朋友越多，奖品越多！",
    invite_bonus_highlight: "+1次旋转, +75 LC & +100 XP",
    invite_stats_total: "总邀请数",
    invite_stats_spins_earned: "获得的旋转次数",
    invite_stats_lc_earned: "获得的Lux金币",
    invite_link_title: "您的邀请链接",
    invite_manager_title: "邀请管理器",
    invite_guest_label: "受邀者",
    invite_date_label: "邀请日期",
    invite_status_label: "状态",
    invite_reward_label: "奖励",
    status_pending_confirmation: "等待确认",
    status_confirmed_paid: "已确认并支付",
    invite_no_referrals: "您还没有邀请任何人。分享您的链接开始赚钱吧！",
    invite_share_text: "您的朋友 {name} 邀请您加入Lux Brasil！💎✨ 使用他们的代码注册即可获得一次免费旋转。快来赢取惊人奖品！",
    status_confirmed: "奖金已支付",
    status_registered: "注册已验证",
    status_rewarded: "已收到奖金",
    status_pending_invite: "待定",
    admin_panel: "控制面板",
    admin_title: "管理",
    btn_update: "刷新",
    tab_users: "用户",
    tab_config: "轮盘配置",
    tab_audit: "审计日志",
    tab_validate: "验证任务",
    search_placeholder: "按姓名、电子邮件或CPF搜索...",
    total_label: "总计",
    table_user: "用户",
    table_cpf: "CPF",
    table_balance: "余额/旋转",
    table_ip: "IP地址",
    table_actions: "操作",
    status_banned: "已封禁",
    status_active: "活跃",
    new_prize: "新奖品",
    prize_active: "在轮盘上活跃",
    btn_save: "保存",
    btn_cancel: "取消",
    lbl_prob: "概率（0-1）",
    lbl_color: "颜色（十六进制）",
    lbl_prize_name: "奖品名称",
    admin_add_coins: "添加Lux金币",
    admin_add_spins: "添加旋转",
    admin_coins_amount: "金币数量",
    admin_preset_loss: "这次没有",
    admin_preset_gold: "黄金",
    admin_preset_silver: "白银",
    admin_central_requests: "兑换中心",
    filter_pending: "待处理",
    filter_paid: "已支付",
    header_date: "日期",
    header_user: "用户",
    header_prize: "奖品",
    header_code: "代码",
    header_status: "状态",
    header_action: "操作",
    type_physical: "实体",
    type_money: "现金/LC",
    type_spins: "旋转",
    btn_pay: "支付",
    btn_refuse: "拒绝",
    btn_reopen: "重新打开",
    empty_requests: "没有待处理的请求。",
    empty_history: "未找到历史记录。",
    stats_total_users: "总用户数",
    stats_coins_circulation: "流通中的金币",
    stats_banned_users: "被封禁的用户",
    tip_prize_active: "提示：如果奖品已经被赢得，您将无法删除它。在这种情况下，请禁用“在轮盘上活跃”选项。",
    config_roulette: "轮盘配置",
    audit_report: "活动报告",
    audit_subtitle: "管理操作的完整日志",
    log_action_update_prize: "奖品编辑",
    log_action_create_prize: "奖品创建",
    log_action_delete_prize: "奖品删除",
    log_action_ban_user: "用户封禁",
    log_action_unban_user: "用户解封",
    log_action_add_spins: "旋转积分",
    log_action_add_coins: "Lux金币积分",
    log_action_ban_ip: "IP封禁",
    log_action_update_redemption: "请求状态",
    dialog_add_spins_title: "添加旋转",
    dialog_add_coins_title: "添加Lux金币",
    table_date: "日期",
    table_prize: "奖品",
    table_code: "代码",
    table_status: "状态",
    table_action: "操作",
    admin_msg_approved: "已批准！",
    admin_msg_rejected: "已拒绝。",
    admin_msg_added_spins: "已添加{amount}次旋转",
    admin_msg_added_coins: "已添加{amount}个金币",
    admin_msg_ban_confirm: "您确定要{action}{name}吗？",
    admin_msg_ban: "封禁",
    admin_msg_unban: "解封",
    admin_msg_ip_ban: "封锁IP {ip}吗？",
    admin_msg_prize_created: "奖品已创建！",
    admin_msg_prize_delete_confirm: "删除奖品？",
    admin_msg_confirm_payment: "确认付款？",
    admin_msg_refuse_request: "拒绝请求？",
    btn_approve: "批准并支付",
    btn_reject: "拒绝",
    table_mission: "任务",
    table_proof: "证明",
    link_view_proof: "查看证明",
    empty_proofs: "没有待处理的证明。",
    btn_edit_user: "编辑用户",
    btn_print_labels: "打印标签",
    push_title: "Lux Brasil",
    push_body_spin: "您的每日旋转现已可用！",
    register_title: "创建账户",
    name_label: "全名",
    cpf_label: "CPF",
    phone_label: "手机",
    invite_label: "邀请码（可选）",
    pass_label: "密码",
    confirm_pass_label: "确认密码",
    already_member: "已经是会员？",
    not_member: "还不是会员？",
    forgot_pass: "忘记密码？",
    create_account_btn: "创建账户并旋转",
    register_success_check_email: "账户已创建！请检查您的电子邮件。",
    err_req: "必填字段",
    err_cpf: "无效的CPF",
    err_pass_match: "密码不匹配",
    err_invite: "无效的邀请码",
    auth_email_confirm: "您的电子邮件尚未确认。",
    auth_invalid_creds: "电子邮件或密码不正确。",
    legal_doc_official: "官方法律文件",
    legal_updated: "最后更新：{date}",
    admin_print_title: "标签 - Lux Brasil",
    btn_print: "🖨️ 打印",
    label_prize: "奖品：",
    label_code_short: "代码：",
    label_tel: "电话：",
    proof_analysis_title: "证明分析",
    proof_context_label: "背景/消息：",
    proof_visual_label: "视觉证明：",
    proof_open_original: "打开原件",
    proof_no_image: "未附上图片。（旧的或纯文本证明）",
    btn_visiting: "验证中...",
    btn_sending: "发送中...",
    upload_click_label: "点击选择图片",
    upload_required: "* 必填",
    admin_override_title: "管理员覆盖",
    profile_avatar_edit: "更改头像",
    profile_info_edit: "个人信息",
    choose_avatar: "选择您的头像",
    joined_date: "加入会员",
    footer_desc: "豪华抽奖的终极体验。注册，旋转独家轮盘，赢取真实奖品。",
    footer_contact: "联系与支持",
    footer_address_label: "商业地址：",
    footer_legal_title: "法律文件",
    legal_privacy: "隐私政策",
    legal_terms: "使用条款",
    legal_data: "数据政策",
    legal_rules: "竞赛规则",
    footer_rights: "版权所有。",
    developed_by: "以精准和奢华开发。",
    spinning: "旋转中...",
    spin_btn: "旋转",
    level_silver: "白银",
    level_gold: "黄金",
    level_platinum: "白金",
    next_level: "距离下一级还差 {xp} 经验值",
    recent_activity: "最近活动",
    no_activity: "尚无活动。",
    notification_missions_approved: "您有 {count} 个已批准的任务待领取！",
    notification_mission_completed: "任务完成：{name}！",
    your_spins: "您的旋转次数",
    available: "可用",
    next_refill_in: "下一次免费旋转倒计时",
    redeem_now: "立即兑换",
    ready_to_use: "您有可用的旋转次数！",
    go_to_roulette: "前往轮盘",
    try_again_title: "下次好运",
    consolation_prize: "安慰奖",
    congrats: "恭喜，您赢了！",
    you_won_label: "您赢得了",
    balance_updated: "您的余额已更新。",
    close_and_continue: "关闭并继续",
    no_spins_title: "旋转次数已用完",
    no_spins_desc: "您没有可用的旋转次数。完成任务或等待下一次每日旋转以继续。",
    btn_go_challenges: "查看任务",
    prizes_title: "我的奖品",
    prizes_empty: "您还没有赢得任何奖品。",
    label_code: "代码",
    msg_redemption_sent: "兑换请求已发送！请跟踪状态。",
    cost_label: "成本",
    btn_redeem_item: "交换金币",
    vault_title: "特权商店",
    vault_subtitle: "使用您的Lux金币兑换独家奖品或更多旋转次数。",
    vault_exchange_success: "兑换成功！您的旋转次数已添加。",
    vault_exchange_error: "兑换错误。请检查您的余额并重试。",
    purchase_success: "成功兑换 {item}！请检查您的钱包。",
    purchase_money_success: "成功兑换 R$ {amount}！请检查您的钱包。",
    store_item_spin_name: "1次额外旋转包",
    store_item_spin_desc: "运气在你这边吗？再来一次旋转轮盘的机会。",
    label_virtual: "虚拟",
    store_item_headphone_name: "高级耳机",
    store_item_headphone_desc: "录音室品质音效，让您完全沉浸其中。",
    label_physical: "实体",
    store_item_earbuds_name: "无线耳塞",
    store_item_earbuds_desc: "为您的日常生活带来自由和清澈的声音。",
    label_money: "金钱",
    store_item_money_name: "R$ 1000.00 信用额度",
    store_item_money_desc: "兑换 R$ {amount} 的信用额度，随心所欲使用。",
    landing_hero_tag: "您的赢奖时刻到了",
    powered_by: "技术支持",
    landing_hero_title_1: "旋转并",
    landing_hero_title_2: "赢取",
    landing_hero_subtitle: "豪华抽奖的终极体验。注册，旋转独家轮盘，安全即时赢取真实奖品。",
    landing_create_account: "创建账户",
    landing_already_member: "已经是会员",
    landing_stat_members: "活跃会员",
    landing_stat_prizes: "已支付奖品",
    landing_stat_secure: "安全与审计",
    landing_why_title: "为什么选择LUX BRASIL？",
    landing_why_subtitle: "独一无二的",
    landing_why_subtitle_highlight: "每个细节",
    landing_feature1_title: "即时访问",
    landing_feature1_desc: "无需等待。注册并立即获得您的第一次免费旋转，开始赢奖。",
    landing_feature2_title: "奖品",
    landing_feature2_desc: "从美食体验到独家产品，或Lux金币。选择不会错。",
    landing_feature3_title: "精英级安全",
    landing_feature3_desc: "您的数据已加密。我们的抽奖算法是透明且可审计的。",
    landing_cta_title: "准备好改变您的运气了吗？",
    landing_cta_subtitle: "今天就加入成千上万的赢家行列。",
    landing_cta_button: "立即旋转轮盘",
    login_welcome_back: "欢迎回来",
    login_err_permission: "权限错误。请联系管理员。",
    login_err_connection: "内部连接错误。请尝试刷新页面。",
    login_err_conflict: "创建账户时发生冲突。请尝试登录或联系支持。",
    auth_err_unknown: "未知的身份验证错误。",
    err_name_short: "姓名太短",
    err_name_full: "请输入您的全名（姓名）",
    err_cpf_format: "CPF格式无效",
    err_phone_short: "电话号码不完整",
    err_phone_invalid: "电话号码无效",
    err_email_invalid: "电子邮件无效",
    err_pass_short: "最少6个字符",
    err_create_account: "创建账户时出错。",
    err_ip_limit_exceeded: "IP地址已超出账户数量限制。请联系支持人员。",
    register_success_title: "请检查您的电子邮件",
    register_success_body: "我们已向您的地址发送了专属确认链接。",
    register_success_warn_title: "注意：",
    register_success_warn_body: "查找来自LUX BRASIL的电子邮件。如果找不到，请检查您的垃圾邮件或垃圾文件夹。",
    register_back_to_login: "返回登录",
    dashboard_greeting: "您好, {name}！",
    dashboard_subtitle: "您的奖品之旅从这里继续。",
    dashboard_vip_panel: "VIP面板",
    dashboard_level: "等级",
    dashboard_xp_total: "总经验值",
    dashboard_prize_log: "奖品日志",
    admin_roulette_subtitle: "管理物品、概率和权重。",
    admin_edit_prize: "编辑奖品",
    admin_prob_hint: "概率 (0.1 = 1%, 1.0 = 10%)",
    admin_type_label: "类型",
    admin_value_label: "价值 (数量)",
    admin_image_url_label: "图片URL",
    admin_description_label: "描述",
    admin_prize_updated: "奖品已更新！",
    admin_contact_whatsapp: "在WhatsApp上联系",
    admin_contact_btn: "联系",
    rarity_legendary: "传奇",
    rarity_epic: "史诗",
    rarity_rare: "稀有",
    rarity_common: "普通",
    audit_target: "目标",
    audit_details: "详情",
    admin_ip_banned: "IP已封禁。",
    admin_challenge: "挑战",
    admin_download_image: "下载图片",
    admin_processing: "处理中...",
    admin_tab_themes: "活动/主题",
    admin_themes_title: "主题和活动配置",
    admin_maintenance_title: "维护模式（系统）",
    admin_maintenance_desc: "启用此选项以阻止普通用户访问。只有管理员才能通过维护屏幕上的秘密登录路径访问平台。",
    admin_maintenance_active: "⚠️ 维护中",
    admin_system_online: "系统在线",
    admin_theme_active: "主题已激活",
    admin_theme_inactive: "主题未激活",
    admin_select_theme: "选择主题",
    theme_default: "默认（无）",
    theme_carnival: "嘉年华（五彩纸屑+紫色/绿色）",
    theme_custom: "自定义（脚本/CSS）",
    admin_save_config: "保存配置",
    admin_config_saved: "系统配置已成功保存并应用！",
    admin_config_error: "保存配置时出错：{error}",
    admin_amount_label: "数量",
    invite_competition: "竞赛",
    invite_performance: "表现",
    invite_friends_unit: "朋友",
    invite_new_player: "新玩家",
    invite_vip_access: "您的VIP访问权限",
    invite_share_to_earn: "分享以获得奖励。",
    invite_total_earnings: "总收益",
    invite_your_achievements: "您的成就",
    xp_label: "经验值",
    invite_effectiveness: "效率",
    invite_confirmation_rate: "确认率",
    invite_of_invites: "的邀请",
    maintenance_title: "我们正在打磨钻石",
    maintenance_subtitle: "我们的团队正在进行独家改进，以确保您的体验更加璀璨和安全。",
    maintenance_status: "状态：装甲更新",
    maintenance_back_soon: "我们马上回来。",
    maintenance_staff_access: "限制区域/员工访问",
    support_title: "Lux支持",
    support_greeting: "你好！我是Natália。点击寻求支持。",
    support_tooltip_benefits: "每日福利 🎁",
    support_tooltip_vip: "VIP Telegram群组 💎",
    support_tooltip_charity: "慈善行动 ❤️",
    support_tooltip_benefits_short: "福利",
    support_tooltip_vip_short: "VIP",
    support_tooltip_charity_short: "慈善",
    progression_title: "声望之旅",
    progression_subtitle: "您在Lux世界中的进化将解锁专属优势。",
    tier_bronze: "青铜",
    tier_gold: "黄金",
    tier_platinum: "白金",
    tier_master: "大师",
    level_perks: "等级福利",
    level_perks_by_tier: "各等级福利",
    perk_levelup_reward: "每升一级奖励50个Lux币。",
    perk_bronze_consolation: "未中奖旋转补偿10个Lux币。",
    perk_gold_consolation: "未中奖旋转补偿15个Lux币。",
    perk_platinum_consolation: "未中奖旋转补偿20个Lux币。",
    perk_master_consolation: "未中奖旋转补偿30个Lux币。",
    perk_master_xp_boost: "每次轮盘旋转奖励50点经验值。",
    you_are_here: "你在这里",
    badges_title: "获得的徽章",
    no_badges: "继续您的旅程以解锁稀有徽章。",
    badge_master_roulette_name: "轮盘大师",
    badge_master_roulette_desc: "授予达到平台最高等级的精英会员。",
    xp_for_next_level: "下一级所需经验值",

    // 新的IP翻译
    IP_LIMIT_REACHED: '已达到此IP地址的注册限制。请联系支持。',
    IP_MISSING: '无法识别您的IP地址。请检查您的连接。',
    err_ip_blocked: '由于注册尝试次数过多，此IP已被阻止。',
    err_email_exists: '此电子邮件已被注册',
    err_cpf_exists: '此CPF已被注册',
    err_phone_exists: '此电话号码已被注册',
    err_duplicate_data: '发现重复数据',
    err_check_data: '验证数据时出错。请重试。',
    err_signup_failed: '注册失败。请重试。'
  }
};